### ISSUE TITLE
Navigation bar links does not work

### ISSUE THREAD

**Issue by choyiny** [fossasia/gci15.fossasia.org#101]
Navigation bar links will not jump to the appropriate anchors

**Comment by pythad** [comment]
@hkminegod, are you sure? It seems everything works fine.

**Comment by choyiny** [comment]
@pythad I am positive.

I am using Mac OSX 10.11.1 Google Chrome Version 47.0.2526.106 (64-bit). The navigation bar links does not respond at all, however the URL will change.

**Comment by ghost** [comment]
@hkminegod 
Running El Capitan as well & website works fine on Chrome

**Comment by ghost** [comment]
@hkminegod The website is pretty heavy, which causes a significant delay in the beginning. However, I did not notice any issues on the setup mentioned above. This is likely not an issue with the website.

**Comment by roonyh** [comment]
This is probably because website not being loaded completely when clicked on links. Will close for now. Reopen if you continue to see it.
