### ISSUE TITLE
First slide isn't shown on mobile phones

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#102]
![screenshot_2015-12-20-13-32-38](https://cloud.githubusercontent.com/assets/8452800/11917991/8381ce84-a71e-11e5-81a8-b0f3950ca4ba.png)

**Comment by Yathannsh** [comment]
Hey @PiotrKowalski ,it works fine on my device, could you please try reload the page and check if the problem still pertain?Thanks!

**Comment by mananwason** [comment]
@PiotrKowalski Works fine on my device too.

**Comment by PiotrKowalski** [comment]
It depend on rotation check horizontal or vertical. Vertical is bad on my device

**Comment by mananwason** [comment]
I am also using it in vertical orientation. Looks fine. Maybe some network issue?

**Comment by PiotrKowalski** [comment]
Maybe, I wll check it in home

**Comment by mananwason** [comment]
:+1:

**Comment by ghost** [comment]
I'm having the same problem on vertical orientation...

**Comment by PiotrKowalski** [comment]
Could you tell me a device?

**Comment by ghost** [comment]
Yeah, Android 5.1.1 Cyanogenmod Galaxy S 5, Android 6.0.1 CyanogenMod Nexus 7, and also I checked on a lot of other mobile devices (Android & iOS 9.1.2) and all of them had the first slide missing. This is definitely an issue

**Comment by ghost** [comment]
However after reloading/waiting a bit, all the iOS devices pulled the image. This is probably an issue with the site's weight/size (#121)

**Comment by ghost** [comment]
Sorry to spam, but landscape mode doesn't help on some devices

**Comment by PiotrKowalski** [comment]
There is option called 'edit', a new info you can add after 'ps:' ;)

**Comment by ghost** [comment]
I know, but on mobile, I first have to click desktop mode & then press edit, tbh I'm just lazy... More importantly this issue seems to have been solved

**Comment by PiotrKowalski** [comment]
So, it seems to be solved. I was waiting to refference this issuse with PR so :P
