### ISSUE TITLE
Youtube Placeholder not optimised for mobile

### ISSUE THREAD

**Issue by mananwason** [fossasia/gci15.fossasia.org#114]
![screenshot_20151220-213852](https://cloud.githubusercontent.com/assets/10570249/11918707/95de6c1a-a762-11e5-8560-6c0045a470a5.png)

**Comment by PiotrKowalski** [comment]
You've just made issuse which is solved #98 #91

**Comment by mananwason** [comment]
I believe these are different.

UPDATE : yeah I see that #91 is same. I am closing this :smile:

**Comment by PiotrKowalski** [comment]
:)
