### ISSUE TITLE
Google+ Social Media Placeholder not correctly aligned in Mobile Phones

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#116]
Google+ Social Media Placeholder not correctly aligned in Mobile Phones

![12398600_804854786327732_1080728109_o](https://cloud.githubusercontent.com/assets/9291400/11918762/d1178850-a764-11e5-87e5-dbc4d433b7dd.jpg)

**Comment by PiotrKowalski** [comment]
#98 #91 you've just created issuse which is made

**Comment by jigyasa-grover** [comment]
My bad.
Shall close it.

Thank You @PiotrKowalski for the kind information.
