### ISSUE TITLE
Bad allign twitter, FB and YT on mobile phones in horizontal rotation

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#118]
How do you think is this same issuse as #91 ? I am not sure, if yes I will close.
![screenshot_2015-12-20-17-52-51](https://cloud.githubusercontent.com/assets/8452800/11918946/6f950858-a743-11e5-8558-f8c5ef0727a8.png)
![screenshot_2015-12-20-17-53-06](https://cloud.githubusercontent.com/assets/8452800/11918947/73425e2e-a743-11e5-8381-1cb4002eca82.png)
![screenshot_2015-12-20-17-53-12](https://cloud.githubusercontent.com/assets/8452800/11918948/758d713c-a743-11e5-9363-08e7fa4d8d87.png)

**Comment by jigyasa-grover** [comment]
@PiotrKowalski Should we close this one as the issue seems to have been resolved ?

**Comment by PiotrKowalski** [comment]
If it is solved, yeah I will close it. I don't follow Fossasia Page now.
