### ISSUE TITLE
Slow page speed

### ISSUE THREAD

**Issue by seadog007** [fossasia/gci15.fossasia.org#121]
After lots of commits, the page loading speed is very very slow now.
![screencapture-developers-google-com-speed-pagespeed-insights-1450630390280](https://cloud.githubusercontent.com/assets/5138409/11919167/25cb04a6-a785-11e5-9dd5-fe46ba076f36.png)
![screencapture-developers-google-com-speed-pagespeed-insights-1450630395744](https://cloud.githubusercontent.com/assets/5138409/11919162/01c46282-a785-11e5-97cf-5a96bc49dd97.png)

**Comment by Yathannsh** [comment]
@seadog007 , for now the only way we can fix this is by optimizing images. 
We can't minify CSS and JS currently as the website is in its development stage. Is there any other way you think we can solve this?

**Comment by seadog007** [comment]
@Yathannsh Well, maybe optimize images first, I think it is the major cause for this issue

**Comment by codethejason** [comment]
I think that optimizing pictures may help, but most of the load is taken by the javascript.  

![javascript](http://puu.sh/m2S32/f546818642.png)  

Also, the site is using a lot of 'expensive' animations such as color transitions on hover, so that will definitely be a cause.

**Comment by ghost** [comment]
Is reducing animations a possibility, because this site is almost unusable on low end phones

**Comment by codethejason** [comment]
@funkyDunks I think that reducing animations on a device of smaller width might help with the mobile issue. For the full screen site, some animations can be made more efficient and the animations that do not add to the site can be removed.

**Comment by ghost** [comment]
Do you want to go smaller width or take out animations based on if it's a mobile browser... I'm focussing mostly on the mobile aspect though

**Comment by codethejason** [comment]
What do you mean by smaller width?

**Comment by ghost** [comment]
You said reducing animations on a device of smaller width, so I assumed you meant detecting the window width & determining animations from there

**Comment by codethejason** [comment]
In my opinion it would be best based off of width. It's not always reliable to detect mobile browsers.

**Comment by ghost** [comment]
Can I go ahead and limit animations based on width?

**Comment by codethejason** [comment]
You can submit any changes you'd like and then the FOSSASIA mentors will review your PR.

**Comment by Meta-Maxim** [comment]
Animations aren't the main cause for the slowness, the member images are. You can tell because if you reload the page with cache cleared it will lag until all of the images are loaded.
Solutions:
1. Reduce image quality / size, increase compression
2. Make each list of members collapsable, so it only shows the first 2-3 rows by default, like the Show More Info menu on a Code-In task shown here:
<img width="1115" alt="collapsable menu" src="https://cloud.githubusercontent.com/assets/2924585/11921899/565d5b7c-a75e-11e5-8167-37188fb437e7.png">
This will save space and reduce rendering lag, it will also prevent mobile users from having to scroll for ages to get past a section. 

Now, as I found out this will not completely solve the problem. Most browsers load images even if they aren't currently displayed.

Thats where my bit of .js comes in. I'm currently making a script that would dynamically load the members images only when they are needed. This is how it works: 
1. When the page is built by Jekyll, I don't use specify the src for images, rather I just add a data tag that stores the URL of the image. 
2. The script then constantly checks if the image is in the users view, and if it is, it gives the image it's src and the image then loads. I'll be pushing a test of this some time today or tomorrow. Feedback appreciated! :P

**Comment by Meta-Maxim** [comment]
Whoohoo, it worked! I just doubled the loading speed with my dynamic image loading script.
Results:
<img width="1229" alt="results" src="https://cloud.githubusercontent.com/assets/2924585/11922465/0d469672-a765-11e5-8fbf-193b29cc8dc5.png">

**Comment by Meta-Maxim** [comment]
Also, I'm currently compressing all of the images, don't worry, you'll all still look the same :) (lossless)

**Comment by codethejason** [comment]
Although the experience isn't as fluid as before on a desktop site since some images take about 1 second to load, I think dynamic image loading should definitely be implemented. Plus, after the images are compressed, they should load faster.

**Comment by Meta-Maxim** [comment]
@codethejason Yes, I noticed that too. That's why I immediately took to compressing them all. Some of the student images are over 1000x1000 in size .-. Also this is just a basic loader that I made in a few minutes, I'll make it load the images a little out of the view so that you don't see them load. Also, if we implement the collapsable panels it will work even better.

**Comment by funkyDunks** [comment]
The dynamic image loading is great, and the images definitely need to be compressed (I just realized some were at 6000x4000). The tabs should definitely be implemented, because the experience on mobile is kind of sucks right now.

**Comment by codethejason** [comment]
I, however, do not agree with the section collapse (hiding rows of members) unless the order of the members is random. No matter what the order a student is on the list, he or she should have an equal chance of being viewed. I will push a change that makes the icons smaller on mobile sites though (with lossless image compression it should load fine - if it doesn't we can change it). This is more of an ethical perspective.

**Comment by ghost** [comment]
#102 has been fixed by your implementation

**Comment by Meta-Maxim** [comment]
@codethejason Yeah I just realized that as I posted it :P Nvm about collapsable tabs.

**Comment by Meta-Maxim** [comment]
@codethejason Also yes, if you make the browser window medium, tablet size, the member images are stretched too far to around 500x500 and turn huge.... Should be fixed.

**Comment by codethejason** [comment]
@MaxBorsch Yep, I'll get a fix by today.

**Comment by Yathannsh** [comment]
@MaxBorsch , compressing the available images is feasible but one can't keep compressing images of all the members that will enroll. How about we integrate  a PageSpeed Module to auto-optimize images?

**Comment by Meta-Maxim** [comment]
@Yathannsh How would you implement that in Github pages / Jekyll? Also, it says in the task to make the image the same size and ratio, however I didn't foresee this when I created the first image which was like 600x600, and so everyone else followed and made theirs likewise. Now that all are the new 300x300 size, people will be required by the task to make their image the same size. Also yeah, I'm done compressing. Added img resize+compression, faster by 1% #126

**Comment by Yathannsh** [comment]
@MaxBorsch, I am not sure about implementing PageSpeed on Github pages but it can be implemented on http://gci15.fossasia.org/ atleast. Size/dimensions of the image issue is not issue, I was talking about quality, well now that you have compressed most of them go ahead!

**Comment by seadog007** [comment]
Good job, guys :D
until commit 799fccd
the page speed became
![photo_2015-12-21_21-51-48](https://cloud.githubusercontent.com/assets/5138409/11932017/1b3ca532-a82d-11e5-9862-c4abf5435854.jpg)
![photo_2015-12-21_21-58-43](https://cloud.githubusercontent.com/assets/5138409/11932146/06ba8c18-a82e-11e5-8375-e6decba4f122.jpg)

It increase a lot, but the mobile UX score decrease a little bit :P

**Comment by mananwason** [comment]
@seadog007 Do we need more optimisation? I think it is sufficient. Please run the benchmarks and let us know.

**Comment by mananwason** [comment]
I am closing this for now. The speed of the page looks fine.

**Comment by mananwason** [comment]
okay apparently speed has reduced from before, so we should be still working on this
<img width="1352" alt="screen shot 2016-01-14 at 12 05 13 am" src="https://cloud.githubusercontent.com/assets/10570249/12303849/a5abe3ea-ba52-11e5-9527-eda8114eb173.png">
<img width="1421" alt="screen shot 2016-01-14 at 12 05 22 am" src="https://cloud.githubusercontent.com/assets/10570249/12303850/a6096344-ba52-11e5-8c9f-06d237f6078f.png">

**Comment by yasoob** [comment]
We can minify some of the not-so-regularly updated `js` and `css` files. For instance `loklak.css`, `hover.css`. Hopefully, this will further increase the page load speed.

**Comment by abishekvashok** [comment]
@mananwason got a fix which I think would work, can I?

**Comment by jigyasa-grover** [comment]
Go ahead @Abhi2424shek

**Comment by abishekvashok** [comment]
Thanks @jig08 I am going to minimize all the code, and create a new folder called development where I will put all the development(un-compressed files in it) and that would be fun right :)

**Comment by SaptakS** [comment]
I think the main problem is the images... Most of the images are much bigger than whats needed in the website.. So I guess the sizes can be reduced..

**Comment by abishekvashok** [comment]
@SaptakS would do that too! Be sure to merge less request as I will occassionaly get conflicts as I am modifying large amount of code ok :) @jig08 . I would do it within 20 minutes please accept it then itself before conflicts arise

**Comment by Abhi2424shek** [comment]
Need 10 more minutes coding part done now optimizing images

**Comment by Abhi2424shek** [comment]
Done checkout my PR : https://github.com/fossasia/gci15.fossasia.org/issues/121

**Comment by abishekvashok** [comment]
Any help from mentors would be highly appreciated I give up out of ideas, my each try failed guys :( But still confiendet I could do it tomarrow with all your help @mariobehling @yasoob @shiftsayan @roonyh @jig08 @sudheesh001 @nikunjness can you all shoot some suggestions

**Comment by shiftsayan** [comment]
If you are working with the new images @Abhi2424shek , you could try lossless compression.

**Comment by shiftsayan** [comment]
Google PageSpeed Insights suggests we should minify the code, but we should be careful because some tasks revolve around editing the JS and CSS files. Also, GPSI suggests we should eliminate render blocking JS and CSS in above fold content. 

You could try to implement these changes @Abhi2424shek

**Comment by abishekvashok** [comment]
Done, mentors next I would compress(optimize javascript) Here's link to PR there's also the status so please check them out: https://github.com/fossasia/gci15.fossasia.org/pull/520 . @jig08 @mariobehling @SaptakS @roonyh

**Comment by jigyasa-grover** [comment]
@seadog007 @Yathannsh @codethejason @yasoob @mananwason @shiftsayan @MaxBorsch 
What updates do we have on this issue ?

**Comment by abishekvashok** [comment]
I may help @jig08

**Comment by codethejason** [comment]
We can probably close this issue @jig08. Another issue #700 has already been created, and we can start with those improvements.

**Comment by jigyasa-grover** [comment]
As you say @codethejason .
