### ISSUE TITLE
Padding not equal

### ISSUE THREAD

**Issue by seadog007** [fossasia/gci15.fossasia.org#132]
The padding between footer and social media section
<img width="1280" alt="2015-12-21 1 16 24" src="https://cloud.githubusercontent.com/assets/5138409/11923937/168bf9b8-a7e5-11e5-908d-a0864dd517ca.png">
should equal the padding between slide and mentor section
<img width="1280" alt="2015-12-21 1 16 29" src="https://cloud.githubusercontent.com/assets/5138409/11923933/1317f26e-a7e5-11e5-8979-1d0ee52e2a90.png">

**Comment by yasoob** [comment]
I would love to work on this issue :+1:

**Comment by yasoob** [comment]
This issue has not been resolved. Can we please reopen it? @jig08
