### ISSUE TITLE
Take contributors' details from Github API

### ISSUE THREAD

**Issue by roonyh** [fossasia/gci15.fossasia.org#139]
Maintaining a `contributors.yml` file is unnecessary when we can dynamically get the info from the github api from the client side. Thoughts?

**Comment by jigyasa-grover** [comment]
+1

**Comment by mananwason** [comment]
Actually I was thinking of the same. Why do it manually if we can get the Contributors from the GitHub API? But then there's the question of responsiveness of the website. Already it is getting pretty slow.

**Comment by PiotrKowalski** [comment]
We have to take only id and login from api.  What can we use for that?
PS: link to Git API https://api.github.com/repos/fossasia/gci15.fossasia.org/contributors

**Comment by roonyh** [comment]
@PiotrKowalski I guess we can't limit returned fields for each contributor. But thats not a problem is it? Its a single request. https://developer.github.com/v3/repos/#list-contributors 
Thats probably the api endpoint you use to create `contributors.yml`?

**Comment by PiotrKowalski** [comment]
I thought that there is solution to take only variables. And yes, it is website from I add contributors to contributors.yml

**Comment by seadog007** [comment]
OK, I will do that

**Comment by samarsault** [comment]
+1
