### ISSUE TITLE
Reduce slider image sizes

### ISSUE THREAD

**Issue by roonyh** [fossasia/gci15.fossasia.org#140]
I can see some work is being done in #121 regarding page speed. Shall we start with reducing images sizes in the slider. Its fine even if we lose the quality because some images are just huge. For example [this one](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/img/community.jpg) is 2.7MB! If someone is already upto this feel free to loose some quality.

**Comment by roonyh** [comment]
We could get a decent result with images around 300KB. Can't we?

**Comment by Yathannsh** [comment]
I have compressed them and made them around 400KB, as going less than 400KB is compromising on quality.
