### ISSUE TITLE
Missing Google+placeholder in mobile phones

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#144]
As for desktop website there are placeholders for Twitter, Facebook, Google+ and YouTube, the Google+ one is missing when viewed on mobile phones.

Device: Motorola G 2nd Generation,  5.00-inch touchscreen display with a resolution of 720 pixels by 1280 pixels at a PPI of 294 pixels per inch. 

![12422056_805407439605800_1852005757_o](https://cloud.githubusercontent.com/assets/9291400/11932742/91cbea92-a81d-11e5-97fe-268ece1d4180.jpg)

**Comment by Yathannsh** [comment]
Hi @jig08 , it works fine on my device. What device did you use to view this?
![a6089063-cd3e-4317-918b-749058a90a5d](https://cloud.githubusercontent.com/assets/12641346/11933061/8a435a88-a81f-11e5-821b-fe6981ebcb0e.jpg)

**Comment by jig08** [comment]
@Yathannsh Checked it on Motorola G2 2nd Generation, ain't working.

**Comment by seadog007** [comment]
@jig08 I think you should give the resolution of your device, not the device model :D

**Comment by jigyasa-grover** [comment]
@seadog007 updated.

**Comment by jigyasa-grover** [comment]
Seems to have been resolved.
