### ISSUE TITLE
Footer padding on mobile phones

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#148]
I think that there should be bigger break beetwen them and margin bottom is too big
![screenshot_2015-12-21-17-42-22](https://cloud.githubusercontent.com/assets/8452800/11935834/603ad898-a80a-11e5-89f4-3ac9419e83f5.png)
Everything here is on bootstrap so I suggest you to add icons margin bottom and delete <p> bottom

**Comment by jigyasa-grover** [comment]
Its varying from device to device, I suppose

![12422056_805407439605800_1852005757_o](https://cloud.githubusercontent.com/assets/9291400/11936022/3b2e6e8a-a831-11e5-846f-20c1fae73447.jpg)

**Comment by ghost** [comment]
Could it be the on screen buttons

**Comment by codethejason** [comment]
After the displaying G+ iframe issue is resolved, this one should also be resolved.

**Comment by aayusharora** [comment]
Hi,@jig08, I want to work on it ,Can you assign it to me ?
