### ISSUE TITLE
Favicon Contest

### ISSUE THREAD

**Issue by Meta-Maxim** [fossasia/gci15.fossasia.org#152]
This has been annoying me for a while now, every time I open the website log I see:
<img width="1273" alt="favicon" src="https://cloud.githubusercontent.com/assets/2924585/11938195/12231b70-a7e7-11e5-9761-c1ebdc8fd110.png">
I say it's time we put an end to this. If you have an idea for a favicon, or a complete drawing, post it here. Remember to make it have the ratio 1:1 (square). We will then decide on which one to use.

Here is an example from the previous community site:
<img src="https://raw.githubusercontent.com/fossasia/fossasia.github.io/master/favicon.ico">

**Comment by pythad** [comment]
I think we have to stick with the previous one. It suits the theme very well.

**Comment by Meta-Maxim** [comment]
Ok, I'll make it have transparent bkg and pull. If anyone gets a better idea post it here.

**Comment by roonyh** [comment]
I can see this has been done! (f238973220f9ca38f9fc6f) I will close this. Thanks @MaxBorsch !
