### ISSUE TITLE
Navbar hamburger has disappeared

### ISSUE THREAD

**Issue by pythad** [fossasia/gci15.fossasia.org#157]
There is no navbar hamburger on the main screen of the site now:
![f2mlhby4qzm](https://cloud.githubusercontent.com/assets/10961029/11940871/1245175a-a834-11e5-8eae-7ce1699a5c5f.jpg)
It changes its positions:
![g-axqsunufk](https://cloud.githubusercontent.com/assets/10961029/11940884/2cf42096-a834-11e5-8a85-4f3ef374be0c.jpg)

**But actually it works okay from the browser's adaptive view.**

Could someone also check this?

**Comment by PiotrKowalski** [comment]
1+

**Comment by yasoob** [comment]
I have made a fix. I will submit a pull request shortly! :+1:

**Comment by yasoob** [comment]
dun-dana-dun! Issue resolved! :dancer:
