### ISSUE TITLE
Thank you translations are not lining up

### ISSUE THREAD

**Issue by codethejason** [fossasia/gci15.fossasia.org#159]
Each translation is not vertically centered with the parent div when it displays.

![vertical](http://puu.sh/m4l70/e4fa83e0bb.png)

**Comment by codethejason** [comment]
Making a PR at the moment.

**Comment by roonyh** [comment]
@codethejason Thanks for fixing this. the section looks much better now!! At the moment it scrolls back to the top at the end. Can we make it go round? Like after the last one the first one comes again? I haven't check the code yet so I don't know if its possible at all :)

**Comment by codethejason** [comment]
@roonyh I'm not sure if that's possible with the current CSS we have (have to look into it more), but it will be possible via JS. Should I create a new issue for this?

**Comment by Yathannsh** [comment]
@roonyh , I think I can implement what you suggest  through the current CSS itself. 
Should I directly create a PR or create an issue first as @codethejason suggested?

**Comment by roonyh** [comment]
@Yathannsh excellent! Create an issue and make a PR.
