### ISSUE TITLE
Google Code In padding not same.

### ISSUE THREAD

**Issue by AaskaShah** [fossasia/gci15.fossasia.org#165]
The padding of google code in is not same as others.
Google Code-In:
![screenshot from 2015-12-22 17 40 40](https://cloud.githubusercontent.com/assets/11875217/11955518/9811e7b0-a8d8-11e5-9a39-8536c9f68320.png)

Any other:
![screenshot from 2015-12-22 18 21 51](https://cloud.githubusercontent.com/assets/11875217/11955583/201d8a88-a8d9-11e5-9d74-1756a39ad0ad.png)

**Comment by aayusharora** [comment]
@AaskaShah  ,I think it depends on the number of lines between heading and the button at the bottom ,more the lines more be the upward ness of heading ,The only possibility is to decrease the space between content and heading.Check  #195 pull request.
