### ISSUE TITLE
https website not secure

### ISSUE THREAD

**Issue by choyiny** [fossasia/gci15.fossasia.org#167]
Suggest to change all links to external sites to use https:// instead of http://

**Comment by seadog007** [comment]
These website don't need too much security.
And I think there is only one link that can change to https
https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html#L355

**Comment by choyiny** [comment]
and links to css and js files

Though I agree with you that websites don't need too much security, having all links with https is better than half https and half http, in my opinion.

**Comment by stenvanhouwelingen** [comment]
I fixed it here https://github.com/fossasia/gci15.fossasia.org/pull/196
