### ISSUE TITLE
Feature the FOSSASIA Google Code In Projects on the website

### ISSUE THREAD

**Issue by ghost** [fossasia/gci15.fossasia.org#179]
I see that there is a Student Gallery, but I was wondering if adding a specialized area for the relatively simple projects on Google Code In could be a possibility. I honestly don't know whether the Student Gallery was made for this purpose, but adding student projects would allow potentially new students to see actual examples of the tasks involved, giving way to a higher participation rate. Also, it wouldn't add to much to the site, as most of the projects are already required to hosted. It's a pretty lame idea, but I think it takes away from a lot of the ambiguity and fear newer students may have before participating. 

https://codein.withgoogle.com/tasks/5447791144861696/
https://codein.withgoogle.com/tasks/5995023363473408/?sp-organization=4625502878826496

**Comment by codethejason** [comment]
I think the student projects should all be put into one category. The student gallery seems apt; we don't want to have _too_ many sections.
