### ISSUE TITLE
Add Continuous integration

### ISSUE THREAD

**Issue by roonyh** [fossasia/gci15.fossasia.org#194]
We can add a continuous integration service like [Travis](https://travis-ci.org/) or [Circle-CI](https://circleci.com/). Most important thing we can test is if the site builds with Jekyll. We can also check if the image is 300x300.

**Comment by yasoob** [comment]
We can use Travis for this purpose. Jekyll has [official docs](http://jekyllrb.com/docs/continuous-integration/) for this purpose as well. :+1: And can you kindly check my performance on [this task](https://codein.withgoogle.com/dashboard/task-instances/5403396626448384/?sp-page=1)? :smile:

**Comment by jigyasa-grover** [comment]
+1 @roonyh

**Comment by samarjeet27** [comment]
Interested students can claim this task - https://codein.withgoogle.com/tasks/5149197082820608/

**Comment by roonyh** [comment]
@yasoob I enabled Travis. Could you make a PR adding `.travis.yml`?

**Comment by mananwason** [comment]
@yasoob Please add `.travis.yml`
