### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#209]
I think that social icons are not well located. I think that it should be under links 
![4bdryh](https://cloud.githubusercontent.com/assets/8452800/12004610/708fa5f6-ab67-11e5-8e20-1634e430d78e.jpg)

**Comment by codethejason** [comment]
Try opening http://fossasia.github.io/gci15.fossasia.org. I don't know why the styling hasn't been applied for gci15.fossasia.org. You should see something like this:  
![see something like this](http://puu.sh/m8JVN/ef2761bb42.png).

But design can still be improved. I just want to make sure you see the correct version.

**Comment by jigyasa-grover** [comment]
Similar reason why #205 was closed.

**Comment by jigyasa-grover** [comment]
Btw, I think it has been applied now.The changes are visible at http://gci15.fossasia.org/

![screenshot from 2015-12-26 23 13 36](https://cloud.githubusercontent.com/assets/9291400/12007354/62a9251a-ac26-11e5-8c94-994f48ed8ecd.png)

**Comment by aayusharora** [comment]
No ,they are not applied ,check the snapshot 
![6](https://cloud.githubusercontent.com/assets/12194719/12007614/d167cda2-ac31-11e5-8e48-88630db07cae.PNG)

**Comment by jigyasa-grover** [comment]
@aayusharora I have attached my screenshot as well which distinctly shows the changes applied to the desktop version of [gci15.fossasia.org](http://gci15.fossasia.org/)

**Comment by aayusharora** [comment]
@jig08 yes,you are very correct ,but mine is mobile version which shows it uneven ,I have corrected it here #222

**Comment by aayusharora** [comment]
@jig08 ,in mobile version ,mail icon comes below

**Comment by aayusharora** [comment]
http://aayusharora.github.io/gci15.fossasia.org/ ,it is corrected here ,#222

**Comment by jigyasa-grover** [comment]
@aayusharora :+1: 
Will review the PR #222  :)
