### ISSUE TITLE
Not showing links of students: Facebook, twitter, github, stackoverflow, ...

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci15.fossasia.org#250]
When I got to http://jleow00.github.io/gci15.fossasia.org/#students
And I put the mouse over a student
Then I want to see the icons of the students links: github, twitter, facebook, stackoverflow, ...

Currently I do not see them:
![capture](https://cloud.githubusercontent.com/assets/564768/12017275/bc9e4116-ad54-11e5-999a-96087f4a05de.PNG)

Not working for me: 
- Firefox 43.0.2

Working:
- Opera 34.0.2036.25
- Safari 5.1.7
- Chrome 47.0.2526.106 
- Internet Explorer 11.0.9600.18124

Does anyone have the same issue?

**Comment by jigyasa-grover** [comment]
@niccokunzmann Could you pls elaborate and post corresponding screenshots :)

**Comment by jigyasa-grover** [comment]
@niccokunzmann Works for me.
Chrome Version 47.0.2526.73 (64-bit)

![screenshot from 2015-12-28 15 53 31](https://cloud.githubusercontent.com/assets/9291400/12017334/2da12254-ad7b-11e5-93b0-c7571de7c813.png)

**Comment by niccokunzmann** [comment]
Good, then I can consider it as only wrong for me. I do not know why.

**Comment by jigyasa-grover** [comment]
@niccokunzmann Working perfectly in Firefox 41.0.
![screenshot from 2015-12-28 15 58 59](https://cloud.githubusercontent.com/assets/9291400/12017403/f7bf7d06-ad7b-11e5-92cf-e0b4c68ac36a.png)
