### ISSUE TITLE
Non responsive navbar

### ISSUE THREAD

**Issue by pythad** [fossasia/gci15.fossasia.org#26]
There is something wrong happening with the current nav bar. It has some margin collisions with the slider when it is getting smaller.

Also the logo stays fixed on smaller screens and the nav bar doesn't. It makes the site look bad at smartphones.

As I see one issue is cause because bootstrap-responsive adds:

```
body {
    padding-left: 20px;
    padding-right: 20px;
}
```

and I am not very sure about the other one.

![selection_003](https://cloud.githubusercontent.com/assets/10961029/11832351/15c60cd6-a3c0-11e5-8310-f09dec9f5de9.png)
![selection_004](https://cloud.githubusercontent.com/assets/10961029/11832352/15f7d8f6-a3c0-11e5-8e5a-35f4757b6099.png)

It would be nice if someone fixed it.

**Comment by seadog007** [comment]
@mariobehling So, this issue should be close, right?

Maybe next time you can write your commit title like `Fixed #issueid`, then it will be automatically close.

**Comment by pythad** [comment]
@seadog007 , no, it's not fixed. Code-in image still has absolute position and looks very ugly on small screens.
