### ISSUE TITLE
Empty space on students section

### ISSUE THREAD

**Issue by jQwotos** [fossasia/gci15.fossasia.org#262]
Multiple blank spaces in students section when viewed on Mobile.
Tested on Google Chrome with Nexus 6 emulation.
![dsafdgujfas](https://cloud.githubusercontent.com/assets/15173247/12022617/74bbf27a-ad5f-11e5-8cfe-db13348927b2.PNG)

**Comment by yasoob** [comment]
I am experiencing it too.
