### ISSUE TITLE
Overflow of mentor, student, and contributor related icons on smaller screens

### ISSUE THREAD

**Issue by johngarbi** [fossasia/gci15.fossasia.org#270]
When you hover over a mentor, student, or contributor's  picture on a smaller screen.  The account icons overflow out of the picture div vertically.
![userinfooverflow](https://cloud.githubusercontent.com/assets/3885948/12062018/e21a4b5e-af59-11e5-98f1-963274b6a717.png)

**Comment by codethejason** [comment]
@johngarbi You can close this issue now :).

**Comment by johngarbi** [comment]
Yes, sorry for late reply. :).
