### ISSUE TITLE
GitHub/Twitter/Facebook/Blog icons missing on hover over mentor/student; Links working

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#280]
Checked on browser:
- Chrome Version 47.0.2526.73 (64-bit)
- Firefox Version 41.0

![screenshot from 2016-01-01 18 53 35](https://cloud.githubusercontent.com/assets/9291400/12070980/1013ff68-b0b9-11e5-933d-3dae944d20f9.png)

**Comment by shashank-sharma** [comment]
I guess link is still there but the logo is not visible.

**Comment by jigyasa-grover** [comment]
@shashank-sharma On Point. I will change the Issue #280 title.

**Comment by sh4dowb** [comment]
Time to close this issue :D Fixed by me ^_^
