### ISSUE TITLE
Overlapping of names on smaller devices

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#285]
The names below the pictures in mentors/students section overlap on smaller devices (checked on a 5 inch display) in case of longer names (Screenshot attached)

![12465197_812887782191099_29521530_o](https://cloud.githubusercontent.com/assets/9291400/12073747/c7096578-b154-11e5-9831-e01c6dcb0b15.jpg)

**Comment by aayusharora** [comment]
Hi,@jig08 consider the design #291,I think it should work.
