### ISSUE TITLE
Mercury

### ISSUE THREAD

**Issue by mercuryprasad** [fossasia/gci15.fossasia.org#286]
Adding my info.

**Comment by jigyasa-grover** [comment]
@mercuryprasad Do you wish to send a PR to add your information ?

**Comment by mercuryprasad** [comment]
Yes. I want add my photo on FOSSASIA GCI students folder.

**Comment by jigyasa-grover** [comment]
Hey @mercuryprasad , Are you new to Git/GitHub ?
You need to `Fork` this repository, add your information (`Commit`) and then send a `Pull Request`. 
Creating an issue isn't required. I am closing this issue, hence.
