### ISSUE TITLE
Create a section with loklak peers on site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#295]
The peers API of loklak is described on the site here http://loklak.org/api.html#peers. Available peers are then listed as follows: http://www.loklak.org/api/peers.json

Please create a section on the site with an automatically updated list of peers as a table and include the IP address and "last seen" timestamp.

**Expected Outcome**
- table list of loklak peers
- list gets updated if peers is online or offline or new peer gets added
- offline peers are shown as "offline"
- accepted pull request to site

FYI, the relevant task during Code-In is: https://codein.withgoogle.com/tasks/4908715949948928/

**Comment by Yathannsh** [comment]
This seems interesting. I was just wondering about how one can figure out peers which are online & the ones which are offline? As http://www.loklak.org/api/peers.json only shows the list of peers which are currently available.

**Comment by mananwason** [comment]
@mariobehling I think we can close this via #312
