### ISSUE TITLE
The contributors heading coming out of the div iphone 4 check

### ISSUE THREAD

**Issue by aayusharora** [fossasia/gci15.fossasia.org#303]
![1](https://cloud.githubusercontent.com/assets/12194719/12094260/9db4a162-b32d-11e5-9c15-8c65ee6a0efe.PNG)

**Comment by jigyasa-grover** [comment]
@aayusharora Would you like to work on it ?

**Comment by aayusharora** [comment]
@jig08 ,yes

**Comment by jigyasa-grover** [comment]
@aayusharora Go ahead.

**Comment by aayusharora** [comment]
issue resolved here  #305

**Comment by aayusharora** [comment]
issue resolved here  #305
