### ISSUE TITLE
Navar wraps to a second row on smaller screen

### ISSUE THREAD

**Issue by Meta-Maxim** [fossasia/gci15.fossasia.org#322]
The navbar links wrap to the second line when on a smaller screen. The text size should decrease on smaller screens in order to fit.

<img width="1279" alt="issue" src="https://cloud.githubusercontent.com/assets/2924585/12154408/3e86d2bc-b48d-11e5-8765-71b48c51eff7.png">

**Comment by jigyasa-grover** [comment]
@MaxBorsch Would you like to work on this ?

**Comment by Meta-Maxim** [comment]
@jig08 Yes, I'll fix it.

**Comment by jigyasa-grover** [comment]
Go ahead @MaxBorsch

**Comment by Meta-Maxim** [comment]
@jig08 Fixed in my latest pull. Also made it more stylish on hover.
https://github.com/fossasia/gci15.fossasia.org/issues/348

**Comment by jigyasa-grover** [comment]
@mananwason This issue has still not been resolved.

**Comment by mananwason** [comment]
@jig08 I believe @MaxBorsch has already fixed it. So, that's why I closed this.

**Comment by Meta-Maxim** [comment]
Resolved in #403

**Comment by jigyasa-grover** [comment]
Refer Issue #394  for new design.

**Comment by yasoob** [comment]
I guess this issue is good to close @jig08 :+1: It was solved in #413

**Comment by jigyasa-grover** [comment]
Yeah sure , Thanks for reminding :)
