### ISSUE TITLE
Can't see this repository as github page when I forked it !

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/gci15.fossasia.org#329]
I have forked this repository. It is available on my account. But when I try to view it as github page, It doesn't come-up. Please help.

Thanks in Advance

**Comment by anshuman73** [comment]
Go to the settings and click on "Your site is ready to be published at ........"
And wait for 5-10 mins.

**Comment by anshuman73** [comment]
Forgot to tell you, you need to delete the cname file before you do so.
Ask for more help on irc. and see if you can close this issue. this isn't exactly an issue with the site.

**Comment by roonyh** [comment]
No need to delete the cname file. It up now http://yashkumarverma.github.io/gci15.fossasia.org/

**Comment by YashKumarVerma** [comment]
Finally. The correct method of someone wants to know (like i used to !)
- Make a change in any file to make github pages.

This is what actually worked.
(by the way @anshuman73 , the CNAME file is still there. it has no functionality until configured by domain settings.)
