### ISSUE TITLE
Web Tweets are not responsive

### ISSUE THREAD

**Issue by aayusharora** [fossasia/gci15.fossasia.org#347]
![1](https://cloud.githubusercontent.com/assets/12194719/12206775/c8507e58-b668-11e5-9059-11b48c8d5fe5.PNG)
IPHONE 4 check:
![2](https://cloud.githubusercontent.com/assets/12194719/12206898/98e62e46-b669-11e5-8256-fcd8b48a3a8e.PNG)

**Comment by jigyasa-grover** [comment]
@aayusharora Would you like to work on this ?

**Comment by aayusharora** [comment]
@jig08, yes working on it.

**Comment by jigyasa-grover** [comment]
Awesome !

**Comment by jigyasa-grover** [comment]
@aayusharora Seems to have been fixed, hence closing this one.
