### ISSUE TITLE
Peers table disappearing 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#353]
The Peer-details table disappears when the count of peers is an odd number. 
Thanks to @nikunjness  for spotting this at first. 

![capture](https://cloud.githubusercontent.com/assets/12641346/12215567/6acc6c6c-b6e8-11e5-81d6-aa81c7ef2bcc.PNG)

**Comment by jigyasa-grover** [comment]
@Yathannsh Would you like to work on this one ?

**Comment by Yathannsh** [comment]
Sure, almost done!
