### ISSUE TITLE
Gallery slider indicators take too much space

### ISSUE THREAD

**Issue by pythad** [fossasia/gci15.fossasia.org#357]
Too many projects have been added to the gallery so that now there are too many indicators and it's hard to navigate the slider.

Possible solutions:
- Add auto scrolling functionality to the slider
- Add right and left buttons to make the navigation easier

**Comment by mananwason** [comment]
+1 @pythad. I believe adding left and right buttons seems like a better solution.

**Comment by roonyh** [comment]
+1 for left right buttons!

**Comment by jigyasa-grover** [comment]
+1 from me too !

**Comment by jigyasa-grover** [comment]
Closed erroneously, Apologies !
