### ISSUE TITLE
Raheel's image missing due to change in name

### ISSUE THREAD

**Issue by vicky002** [fossasia/gci15.fossasia.org#366]
URL : http://gci15.fossasia.org/ 
Check the students section. Image of Raheel Saghir is broken due to change in name. 

Previous image : http://gci15.fossasia.org/img/students/raheel102.jpg (Broken)
Images has been updated and name is changed to "Raheel102"

This can be easily fixed. We just need to update the name to "Raheel102"
See : http://gci15.fossasia.org/img/students/Raheel102.jpg

**Comment by jigyasa-grover** [comment]
@vicky002 Would you like to work on it ?

**Comment by vicky002** [comment]
yeah sure. I just forked the repo. I'm on it. Facing network issues currently.

**Comment by jigyasa-grover** [comment]
@vicky002 Go ahead.

**Comment by tansanrao** [comment]
I've already done it in pull request #364

**Comment by jigyasa-grover** [comment]
Thanks @tansanrao .
