### ISSUE TITLE
Re-sizing  issues 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#37]
#### Mobile View

![capture](https://cloud.githubusercontent.com/assets/12641346/11857682/69ed1bae-a480-11e5-8107-eda8814c59bc.PNG)
#### Tablet View

![2](https://cloud.githubusercontent.com/assets/12641346/11857692/904c0382-a480-11e5-9644-2795cabe45c1.PNG)

The assigned column widths take up a lot of space when the website is re-sized  this leads to situation where in the user has to scroll once per member on devices which are  >365 px in width. Approximating a 100 users this can lead to a situation where in the user will have to scroll multiple times in order to move onto another section. Hence, a potential threat to UX

**Comment by pythad** [comment]
@mariobehling, this issue has been already fixed, could you close it?

**Comment by harshkothari410** [comment]
Its fixed I guess commit #51

**Comment by Yathannsh** [comment]
@harshkothari410 it still takes 1 scroll per member 
Check this out : 
![cv](https://cloud.githubusercontent.com/assets/12641346/11890496/1651388a-a57b-11e5-9e16-29b4462e48a8.PNG)
