### ISSUE TITLE
Fix the header of loklak servers to display the correct meaning

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#373]
There are headings on the server table, where it is not clear, what exactly they are displaying. What does "Last seen" mean? Server online since? Or what exactly. Please specify.
![screenshot from 2016-01-10 19 00 26](https://cloud.githubusercontent.com/assets/1583873/12223031/882a7684-b7cc-11e5-980b-cc0985218ae8.png)

**Comment by jmurzaku** [comment]
@mariobehling would this work?

**Comment by yasoob** [comment]
@jig08 This issue is also good to close :+1: Let's squash some issue 'eh? :smile:

**Comment by mananwason** [comment]
Awesome @yasoob Closing!!
