### ISSUE TITLE
Add FOSSASIA newsletter to site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#375]
Sample code of the newsletter is below:

```
<form action="http://news.fossasia.org/subscribe" method="POST" accept-charset="utf-8">
    <label for="name">Name</label><br/>
    <input type="text" name="name" id="name"/>
    <br/>
    <label for="email">Email</label><br/>
    <input type="text" name="email" id="email"/>
    <br/>
    <input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
    <input type="submit" name="submit" id="submit"/>
</form>
```

**Comment by yasoob** [comment]
Hey @mariobehling ! Can we create it in such a way that when the user reaches the bottom, a slider slides in with the prompt to signup? The website is already very heavy. What do you suggest?

**Comment by abishekvashok** [comment]
@mariobehling can I too try it out please! I am good at this! :) I will giv emy task id when my current task at GCI is completed so I will get the points for this issue too!

**Comment by abishekvashok** [comment]
Working on it! @mariobehling my task id is https://codein.withgoogle.com/dashboard/task-instances/4664245534851072/?sp-page=1 , got it please assign this to me

**Comment by abishekvashok** [comment]
Hey done please see it at https://github.com/fossasia/gci15.fossasia.org/pull/486 and since a lot of PR are there please quickly accept it after reviewing @mariobehling @jig08 @sudheesh001

**Comment by abishekvashok** [comment]
See my PR please and review and accept it (if possible and you think it is satisfactory) : https://github.com/fossasia/gci15.fossasia.org/pull/498
