### ISSUE TITLE
Add a lightweight section "Games" to the site or improve it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#377]
- Move all student projects of games into a special dedicated section
- Ensure that the area is loading fast

**Comment by abishekvashok** [comment]
I am working on it

**Comment by JamMurz** [comment]
https://github.com/fossasia/gci15.fossasia.org/pull/390 this issue was solved in this

**Comment by mariobehling** [comment]
Please avoid implementing it in the same way as the student gallery and rather make a static list of projects similar to the photo list of students. The gallery implementation slows down the site and we already have a "student gallery"
