### ISSUE TITLE
Implement a dropdown menu of "Student Projects"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#394]
**Expected Outcome**
- Dropdown menu similar to fossasia.org "Events tab"
- Sub items: Gallery, Loklak Peers, Loklak Search, Student Games
- Add a separate link top tab "GCI 2014" with a link to http://gci14.fossasia.org

**Comment by JamMurz** [comment]
I will work on this

**Comment by jmurzaku** [comment]
@mariobehling i will work on this
