### ISSUE TITLE
Reduce size of pictures to fit 6 in a row and increase number of shown contributors to "all"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#396]
Currently not all contributors are shown with their picture in GCI. Please check out the github API and increase this number to show all contributors.

Also please decrease the size of the pictures to fit more into the row. Below there are only 4 in a row in the given screen resolution.

![screenshot from 2016-01-12 21 15 33](https://cloud.githubusercontent.com/assets/1583873/12275680/ac28add4-b971-11e5-9de1-6d5ce388688c.png)

**Comment by yasoob** [comment]
Just pushed a fix. Let me know if it is missing anything :smile: + GitHub caps the contributor API result to 30 entries only so we can not display all 70+ contributors here.

**Comment by roonyh** [comment]
@yasoob 30 is only the default. https://developer.github.com/v3/#pagination

**Comment by sumsupee** [comment]
I am working on this,  I will include all the contributors.

**Comment by jigyasa-grover** [comment]
PR #444 fixes this.

**Comment by sumsupee** [comment]
Fixed!

**Comment by jigyasa-grover** [comment]
:+1:
