### ISSUE TITLE
Ensure all mentors are added to the site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#397]
List of Mentors

Username, First name, Last name, Github Username
- [x] Abhishek Batra, Abhishek, Batra, @batraabhishek 
- [x] Agon, André, Rebentisch, @agonarch (twitter), @tabesin (github)
- [ ] André Hentschel, André, Hentschel  
- [x] Andreas Bräu, Andreas, Bräu, @andibraeu 
- [ ] Arkodyuti Saha, Arkodyuti, Saha ,
- [x] Arnav Gupta, Arnav, Gupta , @championswimmer 
- [x] Aruna Herath, Aruna, Herath, @roonyh 
- [x] Arunoda Susiripala, Arunoda, Susiripala, @arunoda
- [x] astroiseur, Handoko, Suwono 
- [x] Austin English, Austin, English ,
- [x] chandankumar, Chandan, Kumar,  
- [ ] Coffee Man, Orwa, Diraneyya 
- [ ] Derek 呆, Derek, Dai 
- [x] Diva, Diwanshi, Pandey 
- [x] Doris Lee, Jung Lin (Doris), Lee ,
- [x] Duke Leto, Duke, Leto, @leto 
- [ ] Eden Dang, Phuc Hau, Dang 
- [x] elfgoh, Luther, Goh 
- [x] Gauthamraj, Gauthamraj, Elango 
- [ ] gibtang, Gibson, Tang 
- [x] Gnovi, PRAVEEN, PATIL 
- [x] Harsh Kothari, Harsh, Kothari 
- [x] Harsh Vardhan, Harsh, Vardhan 
- [x] Hong Phuc Dang, Hong Phuc, Dang 
- [x] Hossain Al Ikram, Hossain Al, Ikram 
- [x] Iwan Gabovitch, Iwan, Gabovitch , @qubodup 
- [x] jans, Jan, Suhr 
- [x] Jigyasa Grover, Jigyasa, Grover @jig08 
- [x] Kalpa Welivitigoda, Kalpa, Welivitigoda @callkalpa 
- [x] Ko Ko Ye`, Ko Ko, Ye` @kokoye2007 
- [ ] Lisa, Lisa, Ihde 
- [x] LisaHJ, Lisa, Hui @LisaHJ 
- [x] Manan Wason, Manan, Wason @mananwason
- [x] Mario Behling, Mario, Behling 
- [x] Martin, Martin, Bähr 
- [x] minal, minal, patil
- [x] Mohit Singh Kanwal, Mohit, Kanwal 
- [x] Nicco Kunzmann, Nicco, Kunzmann 
- [x] Nikunj Thakkar, Nikunj, Thakkar 
- [x] Orbiter, Michael, Christen 
- [x] Perados, Diego, Mora Cespedes 
- [x] RafalKowalski, Rafal, Kowalski  @rafalkowalski 
- [x] Rohit Kashyap, Rohit, Kashyap 
- [x] Samarjeet, Samarjeet, Singh @samarjeet27 
- [x] Sambuddha, Basu, Mentor @sammyshj 
- [x] saptaks, Saptak, Sengupta 
- [x] Sayan Chowdhury, Sayan, Chowdhury 
- [x] Sean McGregor, Sean, McGregor @smcgregor 
- [x] Shiluka, Shiluka, Dharmasena @shiluka 
- [x] Sofia, Jihye Sofia, Seo 
- [x] Sudheesh Singanamalla, Sudheesh, Singanamalla 
- [x] Thanish, Muhammed Nizam, Muhammed Thanish 
- [x] Tim R., Tymon, Radzik @tradzik 
- [x] Tuna, Anh-Tu, Nguyen @ngtuna 
- [x] Yeon, Yeonwoon, Jung

**Comment by shiftsayan** [comment]
I am working on this

Could you provide the GitHub usernames of the mentors please, as it is otherwise difficult to trace each one and we cannot be sure which username is the correct one.

Also, there are a two entries in the above list for  "Mohit Kanwal". Could you please check that out?

**Comment by mananwason** [comment]
Awesome @shiftsayan !! I have updated the list with some of the mentors Usernames

**Comment by shiftsayan** [comment]
I have submitted PR #420 to add 12 mentors.
Will add more if I can find credible links to their profiles and as the above list is updates :)

Also, please clarify about the following entries, I guess they are repetetive.
Sean McGregor, Sean, McGregor
SeanAdmin, Sean, McGregor @smcgregor

Thanks!

**Comment by smcgregor** [comment]
Backstory on why I have so many names:

The GCI site has separate user accounts for admins and mentors because you cannot convert a mentor account into an admin account. So I started out with "Sean McGregor," then attempted to create an admin account under the Google apps account provided by my university, but the authentication was not working for GCI under the university account, so I created another account under a defunct gmail account. So all the entries are mine, but all my mentor communications are under the non-admin account of "...@seanbmcgregor.com".

**Comment by shiftsayan** [comment]
So, we have to add you twice to the mentor list on the website? @smcgregor

**Comment by jigyasa-grover** [comment]
I don't think that should be done :)

**Comment by smcgregor** [comment]
I believe one entry is sufficient :)

**Comment by shiftsayan** [comment]
Alrighty! Could other mentors please add their URLs so that this issue can be closed?

**Comment by qubodup** [comment]
Hello, unfortunately I was busy and confused (I have never mentored any online projects and could find time to try to figure out what I was expected to do) so I ended up doing nothing so I should definitely not be given any credit for this session.

**Comment by abishekvashok** [comment]
I would go with Manan Wason he's great @mariobehling (only after my current task is accepted) so please wait till then

**Comment by shiftsayan** [comment]
Manan Wason has already been added as of PR #420 . You could try the ones not checked and not included in the description of that PR. 

Also could the admins please check the mentors who have been added so as to not cause confusion?
and also update the list with URLs of the few remaining?

**Comment by Abhi2424shek** [comment]
Ok are you a mentor @shiftsayan

**Comment by shiftsayan** [comment]
Nope @Abhi2424shek

**Comment by mananwason** [comment]
@shiftsayan Could you update the list of mentors that you have added in your PR? Thanks!

**Comment by shiftsayan** [comment]
@mananwason I am unable to check the boxes, maybe I do not have the privileges to edit.
Here is the list of mentors I added across 2 PRs:
Jan Suhr
Duke Leto
Iwan Gabovitch
Kalpa Welivitigoda
Lisa Hui
Manan Wason
Rafał Kowalski
Samarjeet
Sambuddha Basu
Tymon Radzik
Anh-Tu Nguyen
Michael Peter Christen
Handoko Suwono
Abhishek Batra

**Comment by mananwason** [comment]
Nice work. I have updated the list :+1:

**Comment by abishekvashok** [comment]
I am really happy on your contribution @shiftsayan but be sure to leave some mentors to be added by other students ! Anyway nice Work :+1:

**Comment by sumsupee** [comment]
Hello! I've added seven more mentors from the list.
Yeonwoon Jung
Jihye Sofia Seo
Diego Mora Cespedes
Gauthamraj Elango
Luther Goh 
Diwanshi Pandey
Austin English
I could add only seven as I could not find accurate accounts on Github of the rest of the mentors who are still left out.

**Comment by abishekvashok** [comment]
mention the PR link @sumsupee

**Comment by sumsupee** [comment]
@Abhi2424shek Here is the link-   https://github.com/fossasia/gci15.fossasia.org/pull/470

**Comment by abishekvashok** [comment]
@sumsupee Mario behling has accepted it! Keep it up! Great!

**Comment by Abhi2424shek** [comment]
More help wanted! And I am there ok, @sumsupee

**Comment by Abhi2424shek** [comment]
@mariobehling here's one more (I have included - Agon)

**Comment by mananwason** [comment]
@Abhi2424shek I have updated the list till the last commit. Please see to it that you atleast include the github profile for the mentors you are adding. Thanks!

**Comment by abishekvashok** [comment]
@mananwason please see to it that you have accepted my PR and note:  Agon and Lisa mentors are already there and about sqaushing can't do it beacse when I squash two commits I get a third commit holding the changes of the 1st and 2nd commits

**Comment by sumsupee** [comment]
@mariobehling @mananwason Hello! The wrong mentor-Andre has been checked in the list. It is André Rebentisch who is currently there on the GCI FOSSASIA website and not Andre Hentschel.

**Comment by jigyasa-grover** [comment]
@sumsupee Corrected :)
