### ISSUE TITLE
Using this to create another website

### ISSUE THREAD

**Issue by Daksh** [fossasia/gci15.fossasia.org#415]
Well I am wanting to create a website for Google Code In 2015, for some other organisation. I know that the LICENSE, of this website does let me use the code. But I still wanted to ask if you guys would mind if the design of the website would look similar? I would be of course changing all the fossasia related content and data and replacing it by the other org's and deleting quite some stuff from it.

**Comment by mananwason** [comment]
@Daksh Go ahead!! The main point of Open source is that anyone can view and use the code after giving proper credits. :smile:

**Comment by Daksh** [comment]
Also, I was wondering if it will be required to keep all the commit history, because I have to anyways remove a lot of things so a lot of commits would practically be undone. I will make sure to not remove any names or license from the files though.

**Comment by yasoob** [comment]
@Daksh IMO it is OK to remove the commit history. Just make sure that you keep the license intact. That is the important thing :smile: Am I right @mananwason ?

**Comment by Daksh** [comment]
@yasoob Alright thank you. and yes I did keep the LICENSE intact, https://github.com/Daksh/SugarLabsGCI2015 
@mananwason Kindly confirm and let me know, and then I will close this issue :)

**Comment by mananwason** [comment]
Yes @Daksh you can modify the code however you like if you are giving proper credits. But as I can see, you have copied code from this repo to yours, that is not the way to use someone's code. Please create a fork of this repo and then you can work on that fork, however you like after keeping the license and giving the credits. Cheers!

**Comment by Daksh** [comment]
@mananwason Alright, I can do that but there is just one mild problem there. Your repository is sort of heavy because of the data of all the students and mentors, the data as in the images. But for my current repo I would not require all those images. Adding that would increase the size of the repo and when someone clones it, though the files are not there it would clone that afaik, because it is git. Is there a way out of that?

In case there is no way, and you want me to keep the commit history, just let me know and I will rebase it.

**Comment by mananwason** [comment]
@Daksh I just mean that should fork this repo and then if you want you can remove the images, add your own.

**Comment by Daksh** [comment]
@mananwason But if I do fork, and even if I delete the images, they would still be uploaded cause git keeps the history and the files which have been deleted. That would increase the repo size.

**Comment by mananwason** [comment]
No @Daksh You can always configure git to not track deleted files anymore. It does keep the history but not on your machine.

**Comment by Daksh** [comment]
@mananwason Can you please give me a link on how that is done? I am currently trying to rebase it and stuff but what you said seems pretty useful for me.

**Comment by Daksh** [comment]
@mananwason Though note, that I would like the new files that I add and delete to still be tracked

**Comment by mananwason** [comment]
Yes @Daksh. You can try [this](http://stackoverflow.com/questions/18549407/how-to-untrack-all-deleted-files-in-git) and [this](http://www.commandlinefu.com/commands/view/1246/git-remove-files-which-have-been-deleted) out.

**Comment by Daksh** [comment]
@mananwason that is git add -u but that would just be for adding the files that I make in a commit, how would it remove the removed files from all the commits that have been done? I have been trying that for the past 30 minutes now. `reb` branch https://github.com/Daksh/SugarLabsGCI2015/tree/reb is what I am working on. I used the git add -u but it does not do what it is required to.

**Comment by Daksh** [comment]
@mananwason I cross checked and it still downloads all the data. When I clone it on a different machine.

**Comment by Daksh** [comment]
@mananwason I also tried to make a gitignore, with adding an ignore for the images folder and then rebasing alll the commits over it but the problem is that the commits in themselves have loads and loads of clashes so I could not do it http://fpaste.org/311145/14528524/ though I spent like a lot of time resolving the clashes which stopped the rebase but they are so many that I cannot resolve all of them. Is it absolutely necessary to do this?

**Comment by mariobehling** [comment]
@Daksh Please go ahead and fork the repo. Of course you can also copy it, but in this case you need to find a way to keep the list of all the contributors in order to give attribution as required by the license. Cheers.

**Comment by Daksh** [comment]
@mariobehling @mananwason I fixed it and now it has all the names of the contributors https://github.com/Daksh/SugarLabsGCI2015/tree/gh-pages have a look? Though it does not have the latest commits, because I have not used them.

Just fyi, I used the command `git filter-branch --tree-filter 'rm -rf img' HEAD` on the clean fork so as to remove all the images from all the commits, so that the size of the repo reduces, and as I do not use those files anymore.

Kindly verify the repo I have and the history, if it looks fine to you. Once you do I will close this issue. 
Thanks for all the help.
Cheers

**Comment by eMBee** [comment]
it would be nice if in the readme, and possibly on the site itself (somewhere in the footer or an about page) you could mention that your site has been built based on FOSSASIAs GCI site.

to the above discussion i'd like to add that there is absolutely no license requirement to keep the history. given that with filter-branch you are rewriting every history entry anyways, i wonder if it was worth the effort.

as for github forking, i believe that if you fork the repo, and then delete all the history, replacing it with your own, github will continue to show that the repo has originally been forked from here. would have been nice, but again there is no license requirement for that.

**Comment by Daksh** [comment]
@eMBee The problem is, that I had to do the filter branch, but I think it would still give the proper attributions? Because all I did was remove the images dir, and all the history and git blame works for all other files that there are in the repo. The problem with not doing the filter is that the repo size which currently is about 15 mb would bloat to about 90 mbs.

I would add the mention in the readme. would that be enough?

**Comment by eMBee** [comment]
given the target audience, adding a link on the website somewhere would be the best.
since your site, like this one is for students learning about Free Software, showing them how the site was created is very meaningful.

a reference in the readme for those who check the source would of course be good too.

**Comment by jigyasa-grover** [comment]
+`1 @eMBee

**Comment by mananwason** [comment]
@Daksh I think we can close this now. Cheers!

**Comment by Daksh** [comment]
https://github.com/Daksh/SugarLabsGCI2015/commit/f1d1d822e8fcab7b4b79a40fa8731686dcbfaa6b added it in this commit :D @mananwason @jig08 @eMBee 
Cheers!
