### ISSUE TITLE
"Other Links" div is not displayed properly

### ISSUE THREAD

**Issue by codethejason** [fossasia/gci15.fossasia.org#423]
In the footer, the links are squashed next to each other. Instead, they should display as one column and each link should have a dedicated line.  

![links](http://puu.sh/muWd6/af5abc75d5.png)

**Comment by rohythakur** [comment]
I am starting to work on this

**Comment by shiftsayan** [comment]
<img width="1280" alt="screen shot 2016-01-14 at 6 02 22 pm" src="https://cloud.githubusercontent.com/assets/8451336/12324504/0025e334-bae9-11e5-8d10-5709380185d2.png">

It is being displayed properly on Chrome Version 47.0.2526.111 (64-bit).

Was it fixed or is it a cross-browser issue like #424 ?
