### ISSUE TITLE
Am I the only one for whom the dropdown in the header is not showing properly?

### ISSUE THREAD

**Issue by shiftsayan** [fossasia/gci15.fossasia.org#424]
<img width="1280" alt="screen shot 2016-01-14 at 12 16 40 pm" src="https://cloud.githubusercontent.com/assets/8451336/12317628/e928c7b2-bab8-11e5-8bce-748ffb367d06.png">

It is looking fine on my forks, but not on the actual site.

**Comment by jmurzaku** [comment]
me too, this appears to be a chrome only problem for me since it works on safari and firefox.

**Comment by jigyasa-grover** [comment]
+1 .

Working fine on `Firefox Version 41.0`
Erroneous display on `Chrome Version 47.0.2526.73 (64-bit)`

**Comment by yasoob** [comment]
It is working fine for me on Chrome 45.x (64-bit) on Ubuntu. 

![nav](http://imgur.com/DH04Aau.png)

**Comment by shiftsayan** [comment]
I cleared my cache and tried again and it works fine! That is why it was working correctly on other browsers! @jig08 

Closing.
