### ISSUE TITLE
Improve dropdown menu

### ISSUE THREAD

**Issue by samarsault** [fossasia/gci15.fossasia.org#448]
The dropdown menu doesn't match with the design.
<img width="224" alt="screen shot 2016-01-15 at 10 00 26 pm" src="https://cloud.githubusercontent.com/assets/2987087/12358490/7689de64-bbd3-11e5-807a-a28c0300a429.png">
Also, it's really cluttered. Please improve that.

**Comment by abishekvashok** [comment]
See it at Abhi2424shek.github.com/gci15.fossasia.org and check it out looks fine!

**Comment by samarsault** [comment]
Great ! Maybe my browser was showing me that earlier due to cache.

**Comment by abishekvashok** [comment]
@samarjeet27 are you a mentor for GCI

**Comment by samarsault** [comment]
@Abhi2424shek Yes.

**Comment by abishekvashok** [comment]
Then can you help me in minizmizing javascript in Jekyll @samarjeet27
