### ISSUE TITLE
Add both links a) web project and b) code into gallery, games and geolocation section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#455]
Expected outcome:
- Projects should work as web links (if it is a web project, like most of them)
- There should be a link to the code as well
- These links can be shown as an overlay or below the project

**Comment by Abhi2424shek** [comment]
what did you actually mean by the above

**Comment by SilentFlame** [comment]
@mariobehling  can you please be a bit more descriptive about this issue.
would like to work on this issue.
