### ISSUE TITLE
Create a section "lights out" of student projects with at least 10 sites done at the contest

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#456]
We had a lot of students who created sites with Javascript called "Lights Out". Find at least 10 (or more if possible) and add a screenshot, link to repository and link to the actual website to the GCI site.

Expected Outcome:
- static section "lights out"
- screenshot of projects 
- link to actual site (web project) of a student
- link to code repository
- minimum 10 projects (check out what you find on twitter for example of students)

**Comment by abishekvashok** [comment]
hey can you assign this to me @mariobehling would do it as my current ask is submitted for review (which would be mostly accepted and you too is a mentor on the task) and it would be nice if you could add another issue after this to improve the light's out section. Lastly do you want it be a photostack.js gallery (which we currently have) or another gallery type (using the photostack.js would save page load time) .

**Comment by jmurzaku** [comment]
i claimed this task already on gci sorry @Abhi2424shek

**Comment by abishekvashok** [comment]
No worries go on man! you will succeed, go ahead, best of luck

**Comment by abishekvashok** [comment]
I also would get that task :) @JamMurz

**Comment by jmurzaku** [comment]
@Abhi2424shek thanks, and sorry it was my fault for not writing that i claimed the task :)

**Comment by jigyasa-grover** [comment]
Seems to have been fixed.
