### ISSUE TITLE
Something wrong with avatar circles

### ISSUE THREAD

**Issue by pythad** [fossasia/gci15.fossasia.org#47]
With recent commits the design has slightly changed and also something wrong has been done with avatar circles, there are ellipsis now and they look very bad.
![ellipsis](https://cloud.githubusercontent.com/assets/10961029/11878311/af0b9756-a4fd-11e5-9546-1f90528ae541.png)

**Comment by harshkothari410** [comment]
I don't find this bug. Can you be more specify ?

**Comment by pythad** [comment]
@harshkothari410, it seems it's fixed now. I think it existed because cloudfare had't updated stylesheets so fast, sometimes it happens. I close this.
