### ISSUE TITLE
Section- Styling Issues

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#473]
There remains no padding between the two sections
![capture](https://cloud.githubusercontent.com/assets/12641346/12377007/849abd5a-bd33-11e5-9db0-dee92e8a0444.PNG)

Also the Lights-out section & social media section are merged together, which looks ugly.

![hg](https://cloud.githubusercontent.com/assets/12641346/12377033/e6496e34-bd33-11e5-8407-d2e0b6d71ffb.PNG)

**Comment by jigyasa-grover** [comment]
@Yathannsh Would you like to work on this ?

**Comment by Yathannsh** [comment]
Sure! Right onto it! :+1:

**Comment by jigyasa-grover** [comment]
Awesome !

**Comment by yasoob** [comment]
@jig08 This issue is good to close :+1: 

@Yathannsh if your commit closes an issue then add "closes #issue_numer" instead of "fixes #issue_number" in your commit message. This automatically closes the respective issue when your commit is merged. :smile:

**Comment by jigyasa-grover** [comment]
@yasoob Thanks. For the reminder and also for the tip. @Yathannsh Keep that in mind :)
Good going everyone !

**Comment by Yathannsh** [comment]
Will keep that in mind. Thanks @jig08 @yasoob!
