### ISSUE TITLE
Create a section with static gallery with student stickers made in the Privly task

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#476]
Stickers were made in this task: https://codein.withgoogle.com/tasks/5632184761188352/

**Comment by Yathannsh** [comment]
Where can we find these stickers?

**Comment by Yathannsh** [comment]
Where can these stickers be found?

**Comment by Yathannsh** [comment]
Working on this

**Comment by Yathannsh** [comment]
@mariobehling This can be closed now! :+1:
