### ISSUE TITLE
*FOSS Quiz by Zakmon* project in *Geolocation Projects* section

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#477]
Erroneously `FOSS Quiz by Zakmon` project has been added in the `Geolocation Projects` section (refer screenshot attached).

![screenshot from 2016-01-17 18 16 32](https://cloud.githubusercontent.com/assets/9291400/12377514/b4bb2548-bd46-11e5-91b0-be68b97a4a77.png)

Edit 1: Instead of completely removing it, add it back to the `Gallery` section.
Edit 2: It already exists in `Gallery` hence only removal from `Geolocation Projects` section shall do

**Comment by sumsupee** [comment]
@jig08 I think it is already there in the gallery. The same image was referenced in the gallery as well as in the geolocation pane. https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/img/gallery/quiz.png
![image](https://cloud.githubusercontent.com/assets/16363810/12377742/98cbd678-bd4d-11e5-80ef-5482191490bc.png)
So I don't think so I need to add it again.

**Comment by jigyasa-grover** [comment]
Cool then !
Will edit the description again . Thanks for pointing that out @sumsupee

**Comment by sumsupee** [comment]
:+1:
