### ISSUE TITLE
Fix heading and reduce the size of top menu header font

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#478]
![screenshot from 2016-01-17 13 52 12](https://cloud.githubusercontent.com/assets/1583873/12377538/b9d749d2-bd21-11e5-808b-d2b0134d9e32.png)
The top heading line does not display properly on smaller screens. Also in the dropdown menu longer subheadings are not correct. See "Geolocation Projects" for example.

**Comment by shashank-sharma** [comment]
@mariobehling  Will that be fine if I edit bootstrap.min.css file ?

**Comment by jigyasa-grover** [comment]
@mariobehling A PR https://github.com/fossasia/gci15.fossasia.org/pull/474 was made (and merged) in this regard by @shashank-sharma and it seemed to fix the issue then

**Comment by yasoob** [comment]
I guess this issue is good to close @jig08 :+1:

**Comment by jigyasa-grover** [comment]
Okay @yasoob . Closing this...
