### ISSUE TITLE
Move contributors to end and reduce to 12 in a row

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#479]
Expected Outcome
- In top menu contributors show up before GCI2014
- change to eight in a row
- section shows at the end up before bottom section

**Comment by shiftsayan** [comment]
I am working on this

**Comment by jigyasa-grover** [comment]
@mariobehling I think we could increase the number of mentors and students from 4 in a row to 5 or 6 in a row, maybe ?

**Comment by Yathannsh** [comment]
@shiftsayan , I am sorry just read this. 
I have implemented 2/3 objectives of this issue in #483 . Could you work on the remaining which is, "change to eight in a row"? Thanks!

**Comment by shiftsayan** [comment]
@mariobehling Bootstrap does not natively support 8 equal columns (since it uses a 12 column system), so we will have to have half width columns or have to use nested columns.

Instead we could do what @jig08 suggested to reduce length of the page

**Comment by mariobehling** [comment]
Please reduce the number of contributors in the column to 12 in a row then. Thank you.
