### ISSUE TITLE
Add Copyright Details

### ISSUE THREAD

**Issue by iKhushPatel** [fossasia/gci15.fossasia.org#508]
I want to add copyright details for the new year of 2016 at the end of website.

**Comment by iKhushPatel** [comment]
@sudheesh001  Can i do this ?

**Comment by yasoob** [comment]
Hey @iKhushPatel Just go ahead and submit a pull request :smile: Best of luck! :+1:

**Comment by Elgayar** [comment]
Hello, I would like to do this issue since it is not done yet, can I?

**Comment by jig08** [comment]
@Elgayar Sure, go ahead. Submit a PR and we shall review :)

**Comment by Elgayar** [comment]
Hey Mentors!
I'm back with a new task done!!! :D It was the silliest actually :P

Pull Request, I have successfully added Copyright Details:
https://github.com/fossasia/gci15.fossasia.org/pull/589

Tweet Link:
https://twitter.com/MostafaaGayar/status/690608510405599232

Demo:
http://elgayar.github.io/gci15.fossasia.org

Thanks!!

**Comment by Yathannsh** [comment]
Can a website be licensed under  GNU GENERAL PUBLIC LICENSE and have copyrights at the same time?

**Comment by mananwason** [comment]
I'm not sure @Yathannsh. @mariobehling @creativepsyco Views?

**Comment by Elgayar** [comment]
I didn't know, if that was right I think this issue shouldn't have been accepted in the first place :D

**Comment by abishekvashok** [comment]
@mananwason here's the data from the faq section of open source : 

**You are not required to claim a copyright on your changes. In most countries, however, that happens automatically by default, so you need to place your changes explicitly in the public domain if you do not want them to be copyrighted.
Whether you claim a copyright on your changes or not, either way you must release the modified version, as a whole, under the GPL. (if you release your modified version at all)**

**Comment by roonyh** [comment]
@Yathannsh Yes. of course the authors can keep copyright and release the code under GPL terms.

**Comment by Yathannsh** [comment]
@roonyh thanks for the clarification! :+1:
