### ISSUE TITLE
Spilling out of names from the respective places

### ISSUE THREAD

**Issue by sumsupee** [fossasia/gci15.fossasia.org#511]
There is a spill of the long names in the website out of their respective containers which makes it a bit messy. It would be better if the names do not interfere with other's profiles or spill out of the page.  
![issue1](https://cloud.githubusercontent.com/assets/16363810/12399721/c1dfaf4a-be41-11e5-8d0b-d9762bb4d4a3.PNG)
![issue2](https://cloud.githubusercontent.com/assets/16363810/12399722/c1e2a57e-be41-11e5-8d5c-13956fe3919d.PNG)

**Comment by jigyasa-grover** [comment]
@sumsupee Would you like to work on this ?

**Comment by sumsupee** [comment]
@jig08 I would like to give others a chance.

**Comment by jigyasa-grover** [comment]
@sumsupee No issues :)

**Comment by shubh1m** [comment]
@sumsupee @jig08 I would like to work upon this.

**Comment by jigyasa-grover** [comment]
@iamshubh22 Go ahead !

**Comment by shubh1m** [comment]
@jig08 it would be better if we skip out the middle names. Keeping in mind another issue #479 the space for each name is going to be even less when there will be 8 names in a row. What's your opinion?

**Comment by yasoob** [comment]
I guess you can specify the width of the container of names without omitting the middle names. Issue #511 will not be resolved anytime soon because Bootstrap does not provide a default class for slicing a row into 8 equal columns. :smile:
