### ISSUE TITLE
Auto cropping images using PIL

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#522]
Hey guys! Can we add a Python script to auto-crop images? I have made a sample script. It is really simple and easy:

``` python

import os
import sys
import Image

crop_size = 240, 240

if len(sys.argv) < 2:
    print "Sorry but you did not specify any filename/s"
    sys.exit()

for infile in sys.argv[1:]:
    outfile = os.path.splitext(infile)[0] + ".jpg"
    if not os.path.exists('cropped'):
        os.mkdir('cropped')
    if infile != outfile:
        try:
            im = Image.open(infile)
            im.thumbnail(crop_size, Image.ANTIALIAS)
            im.save(os.path.join('cropped',outfile), "JPEG")
        except IOError:
            print "cannot reduce size for '%s'" % infile
```

Now you can run this:

``` bash
$ python crop.py filename.jpg
```

You can also specify multiple filenames:

``` bash
$ python crop.py filename.jpg filename2.jpg filename3.jpg
```

**Note:** You need to have PIL and Python installed.

**Comment by pythad** [comment]
Hi @yasoob, I also thought about this ;) Your script won't deal with `.png` or any other than `.jpg` extensions. Can we deal somehow with this?

**Comment by yasoob** [comment]
@pythad My script deals with `png` files as well as `jpeg` files. The hardcoded file extensions make it appear as if it is only for `jpeg` files :smile: Let me put up some updated code.

**Comment by codethejason** [comment]
Looks good - would definitely help with the problem of weirdly sized images if it is run consistently.

**Comment by yasoob** [comment]
Here is the updated code which works for both, jpeg and png, files.

``` python
import os
import sys
import Image

crop_size = 240, 240

if len(sys.argv) < 2:
    print "Sorry but you did not specify any filename/s"
    sys.exit()

for infile in sys.argv[1:]:
    outfile = os.path.splitext(infile)[0] + os.path.splitext(infile)[-1]
    if not os.path.exists('cropped'):
        os.mkdir('cropped')
    if infile != os.path.join('cropped',outfile):
        try:
            im = Image.open(infile)
            im.thumbnail(crop_size, Image.ANTIALIAS)
            img_format = ''.join(['JPEG' if 'jpg' in infile.split('.')[-1] else infile.split('.')[-1].upper()])
            im.save(os.path.join('cropped',outfile), img_format)
        except IOError:
            print "cannot reduce size for '%s'" % infile
```

**Comment by yasoob** [comment]
I don't think we need this for now. If we ever need to implement such a feature in future then we can take a look at [this project](https://github.com/zroger/jekyll-minimagick). It seems quite promising. By using it we can also keep using Ruby and not introduce a Python dependency. :+1:
