### ISSUE TITLE
Newsletter prompt is not user-friendly

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#526]
The newsletter prompt in the footer is not user-friendly. The white color of the button's text makes it unreadable. Additionally, the input color is also white so whatever you write in the input is not visible. Moreover, there should be some margin between the input and the button.
![screenshot from 2016-01-20 01 06 59](https://cloud.githubusercontent.com/assets/3696393/12430618/578fa5d8-bf12-11e5-8130-2c123772dded.png)

**Comment by iamshubh22** [comment]
@yasoob I would like to work upon this.

**Comment by jigyasa-grover** [comment]
+1. This section needs improvement.
@yasoob Why not make a prompt that slides up from the bottom instead of the right side as in your previous PR ?

**Comment by yasoob** [comment]
But it would still cover the footer when it slides in. I don't think I am getting what you are saying.

**Comment by rohangoel96** [comment]
I am working on this.

**Comment by jigyasa-grover** [comment]
@yasoob In your earlier PR, the newsletter prompt used to slide from the right towards the left. Could we make it such that it slides up from the bottom of the page such that it doesn't cover the social media buttons located at the right side ? I hope this is clearer.

@rohangoel96 Sure, send in a PR .
