### ISSUE TITLE
Icon display problem

### ISSUE THREAD

**Issue by seadog007** [fossasia/gci15.fossasia.org#53]
When the icon display, it look like very weird.
- 3:
  <img width="237" alt="2015-12-17 10 51 48" src="https://cloud.githubusercontent.com/assets/5138409/11884412/a946a002-a554-11e5-9693-eb87b94b38c3.png"><img width="277" alt="2015-12-17 10 51 37" src="https://cloud.githubusercontent.com/assets/5138409/11884416/afdc4d54-a554-11e5-8736-67e88d919237.png">
- 4:
  <img width="394" alt="2015-12-17 10 51 29" src="https://cloud.githubusercontent.com/assets/5138409/11884420/b896fa66-a554-11e5-9134-533f43bc3e73.png">

**Comment by Meta-Maxim** [comment]
@seadog007 I'm not sure what you mean by weird, but assuming you meant the way the icons are laid out, yes I agree. Although I think it was intended to be like that. I think they would be better if they were arranged in an arch around the bottom of the circle. Like so (blue = where they should be):
<img width="356" alt="layout" src="https://cloud.githubusercontent.com/assets/2924585/11886610/f6b3370c-a4f9-11e5-9239-e1f7f41c5234.png">

**Comment by seadog007** [comment]
I think because the center icon of first two is not really in center
<img width="296" alt="2015-12-18 1 55 38" src="https://cloud.githubusercontent.com/assets/5138409/11890434/4d8e2236-a58f-11e5-9200-6fd11734f9f8.png"><img width="307" alt="2015-12-18 1 56 34" src="https://cloud.githubusercontent.com/assets/5138409/11890436/51e5e4fe-a58f-11e5-948b-2bcf6c1d191b.png">

**Comment by seadog007** [comment]
And in the last one, the left bottom corner icon didn't match the grid.
<img width="251" alt="2015-12-18 1 59 56" src="https://cloud.githubusercontent.com/assets/5138409/11890478/ce739b42-a58f-11e5-9b44-8995364c37ee.png">

**Comment by codethejason** [comment]
Something like this?  
![image](http://puu.sh/m1hnG/56e69f26be.jpg)

**Comment by seadog007** [comment]
@codethejason I think I should look like original, but it should be align in the grid.
