### ISSUE TITLE
Regarding "View blog posts" section

### ISSUE THREAD

**Issue by shubh1m** [fossasia/gci15.fossasia.org#533]
Number of blogs should be adjusted to 4 in a row.

![screenshot from 2016-01-20 15-51-18](https://cloud.githubusercontent.com/assets/13465950/12446570/c360d2a4-bf90-11e5-90ce-95de4baf87e1.png)
![screenshot from 2016-01-20 15-51-29](https://cloud.githubusercontent.com/assets/13465950/12446571/c3bf6774-bf90-11e5-8a17-9bf58c035dfc.png)

**Comment by mananwason** [comment]
Agreed @iamshubh22. Feel free to fix it :+1:

**Comment by shubh1m** [comment]
@mananwason Ok, I will see to it
