### ISSUE TITLE
Fix section issue e.g. Student Gallery and Loklak Heatmap do not work anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#552]
- [x] student gallery - cannot click on works, no more bottom list, forward/back link does not work
- [ ] student gallery - please move items like games and geolocation projects to other areas
- [x] heatmap - show map and search button again

**Comment by yasoob** [comment]
Loklak Heatmap does not work because the Cloud9 backend-website has been stopped by the owner. Let me see if I can fix it.

**Comment by mariobehling** [comment]
Gallery is not fixed. Issue should not have been closed.

**Comment by yasoob** [comment]
Hey @mariobehling Can we close this issue and only keep #710 open? The remaining issue is almost similar in both of these issues.

**Comment by abishekvashok** [comment]
I think @yasoob is right @mariobehling
