### ISSUE TITLE
Add a fork me on github on the top right

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#558]

**Comment by yasoob** [comment]
I am working on this. :+1:

**Comment by mananwason** [comment]
Awesome @yasoob. Assigning you :smile:

**Comment by yasoob** [comment]
Hey @mananwason @mariobehling  it covers the Google Code-in banner. What do you suggest?
![screenshot from 2016-01-21 22 04 03](https://cloud.githubusercontent.com/assets/3696393/12487912/0265a326-c08b-11e5-906a-b6aee7f38e0d.png)

**Comment by mananwason** [comment]
Can you shift this under the code in batch @yasoob ?

**Comment by yasoob** [comment]
@mananwason I didn't get you. What do you mean by _under the **code in batch**_?

**Comment by jigyasa-grover** [comment]
@yasoob , I guess @mananwason  means beneath the `Google Code-In` badge on the nav bar...

**Comment by mananwason** [comment]
Yes @yasoob I meant beneath the google code in batch

**Comment by yasoob** [comment]
@mananwason Do you mean like this?
![screenshot from 2016-01-21 22 43 34](https://cloud.githubusercontent.com/assets/3696393/12489083/738ee756-c090-11e5-924d-8e702e3a291c.png)

**Comment by mananwason** [comment]
Yea Exactly @yasoob

**Comment by yasoob** [comment]
@mananwason I have submitted a PR :smile:

**Comment by mariobehling** [comment]
Please do not keep the Fork me on Github on the page when the user scrolls up. Expected behaviour: User scrolls up and the bar scrolls below header menu.

**Comment by yasoob** [comment]
That is easy. We just need to set the position to "absolute" instead of
"fixed". I will happily fix it later today.

**Comment by jigyasa-grover** [comment]
@yasoob Cool. Let know when you send an updated PR for this.

**Comment by yasoob** [comment]
@jig08 First let's resolve #572 and then I will submit a PR for this issue :+1:

**Comment by jigyasa-grover** [comment]
Merged #572
