### ISSUE TITLE
Add section "latest issues" to website by using the GitHub API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#559]
**Objective**

Create a section "latest issues" in a sorted list with issues tagged with the label "feature". Please use the [github API](https://developer.github.com/v3/issues/) to get the data

**Requirements**
- use Github API https://developer.github.com/v3/issues/
- website is http://gci15.fossasia.org

**Expected Outcome**
- sorted list of [issues in this repository](https://github.com/fossasia/labs.fossasia.org/issues) labeled "feature"
- include "read more" which links to the issue itself in the tracker
- only show "open issues"

**Links**
- issue tracker https://github.com/fossasia/gci15.fossasia.org/issues/

**Comment by abishekvashok** [comment]
I wanna work in this seems cool

**Comment by mananwason** [comment]
Go ahead @Abhi2424shek.

**Comment by yasoob** [comment]
Hey @Abhi2424shek If you want to use laughing emoji then use this: `:laughing:`

**Comment by abishekvashok** [comment]
Ok @mananwason  to get to the topic, I have a doubt! Ok so should I pickup all the issues which are labeled feature and open of the fossasia organisation or this gci15.fossasia.org repo. Please reply soon :)

**Comment by mananwason** [comment]
@Abhi2424shek It is clearly mentioned in the description by @mariobehling. He has given you the link for this repo's issues.

**Comment by abishekvashok** [comment]
K but there are not tasks labeled 'feature' in the issue's section which are open. Be sure to create some :) . Sorry if the last question was a bit mad one.

**Comment by abishekvashok** [comment]
Done check PR: https://github.com/fossasia/gci15.fossasia.org/pull/602 @mariobehling @mananwason  . Be sure to  rename this issue as improve issues section or create a new issue for other students to work on :) . Lastly thanks for keeping faith in me.
- Enjoying last working days at GCI

**Comment by mananwason** [comment]
Closed via #605
