### ISSUE TITLE
Improving/Reverting the changes done to *Lights Out* section

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci15.fossasia.org#567]
**Edit:** I believe some changes were made to the **Lights Out !** owing to Issue #529 which makes it stand out from others not in a good way. The heading and style doesn't gel with the other sections' formatting.

![screenshot from 2016-01-21 23 33 42](https://cloud.githubusercontent.com/assets/9291400/12489773/fe93bbb8-c097-11e5-80a1-c26d455ee371.png)

---

**Prev:** I believe some changes were made to the **Lights Out !** owing to Issue #529 which makes it look tacky now. 

![screenshot from 2016-01-21 23 23 28](https://cloud.githubusercontent.com/assets/9291400/12489443/67472976-c096-11e5-9d62-a7550d385fcb.png)

**Comment by mananwason** [comment]
@jig08 Seems good to me !! 
<img width="1436" alt="screen shot 2016-01-21 at 11 30 08 pm" src="https://cloud.githubusercontent.com/assets/10570249/12489584/0b60f21c-c097-11e5-896f-3b955f6a53de.png">

**Comment by jigyasa-grover** [comment]
@mananwason Oh Yes, seems to be working fine now. I shall edit the issue.
But In my opinion, the heading and style doesn't gel with the other sections' formatting.

**Comment by mananwason** [comment]
Yes @jig08, I agree. @codethejason is fixing this in #554

**Comment by jigyasa-grover** [comment]
Cool !

**Comment by yasoob** [comment]
Hey @jig08 I shared some of my suggestions in [this PR](https://github.com/fossasia/gci15.fossasia.org/pull/573). What do you think about them?

**Comment by jigyasa-grover** [comment]
Thanks @yasoob :)
Hope incorporating them brings out a better look.

**Comment by jmurzaku** [comment]
@jig08 is this issue fixed now? :smiley:

**Comment by mananwason** [comment]
@JamMurz I think so. We can close this for now.
