### ISSUE TITLE
Duplicate img files in students pics folder

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#570]
Almost every pic has a duplicate. For instance, my profile pic, `yasoob.jpg` has a duplicate named `yasoob-1.jpg`. Where are the duplicate files being used? I did a `grep` but wasn't able to find any place where they are being used. Kindly let me know if they are useless so that I can clean the folder from duplicates.

**Comment by mananwason** [comment]
@yasoob I believe that @Abhi2424shek Didn't delete the older images when he added new one in https://github.com/fossasia/gci15.fossasia.org/commit/56cf2fd0fcfabd7e9bd6901e7504b917c01a3a69

**Comment by yasoob** [comment]
Ok. Let me remove them then. The optimal size for the Profile pics is `240x240`. Right?

**Comment by mananwason** [comment]
yes @yasoob
