### ISSUE TITLE
Make github issues section look nicer 

### ISSUE THREAD

**Issue by jmurzaku** [fossasia/gci15.fossasia.org#612]
![issue](https://cloud.githubusercontent.com/assets/9733795/12531477/c9a070bc-c1c9-11e5-8ff7-55ca53086894.PNG)
currently, when no issues show up on github, it looks like this. Maybe adding larger text and more colorful text would hep and make it look nicer?

**Comment by jmurzaku** [comment]
I can work on fixing this

**Comment by mananwason** [comment]
Go ahead :+1: You can add some catchy phrases as well. Let's see your creativity :stuck_out_tongue_winking_eye:

**Comment by yasoob** [comment]
It appears fine on my end.

![screenshot from 2016-01-23 22 23 56](https://cloud.githubusercontent.com/assets/3696393/12531575/0fc70f3c-c220-11e5-8e3d-8708a2f6cd9a.png)

**Comment by jmurzaku** [comment]
<img width="1132" alt="screen shot 2016-01-23 at 12 26 58 pm" src="https://cloud.githubusercontent.com/assets/9733795/12531594/ac562472-c1cc-11e5-9aad-5dfef7b6dcea.png">
oops, looks good to me now too after i refreshed a couple times. Sorry for that!
