### ISSUE TITLE
Button stopped working in lights section 

### ISSUE THREAD

**Issue by jmurzaku** [fossasia/gci15.fossasia.org#616]
![capture](https://cloud.githubusercontent.com/assets/9733795/12531811/2912524c-c1d2-11e5-85cf-b8e51bbb926f.PNG)
![capture](https://cloud.githubusercontent.com/assets/9733795/12531813/41caa9e2-c1d2-11e5-9b92-e6df526bd3be.PNG)
When I click the button, it does not work anymore. Can I fix this by changing the scope of the function i wrote?

**Comment by jmurzaku** [comment]
@mananwason the button works now, can i close the issue?

**Comment by mananwason** [comment]
Yeah. Go ahead!

**Comment by jmurzaku** [comment]
@mananwason if i find minor issues in the future like this one do i have to open an issue on the repo,or can i just fix the issue without opening an issue?

**Comment by mananwason** [comment]
@JamMurz It would be better if you open an issue, helps us in tracking better.

**Comment by jmurzaku** [comment]
@mananwason ok, thank you very much for your help! :+1:

**Comment by mananwason** [comment]
Great @JamMurz !! My pleasure :smile:
