### ISSUE TITLE
 Newsletter Prompt issues

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#622]
- The Newsletter prompt is not visible on devices with less than a width of 325px
  ![sec4](https://cloud.githubusercontent.com/assets/12641346/12532069/7f711098-c230-11e5-9dba-466bf066c462.PNG)
- The Newsletter prompt is unresponsive on devices with a width greater than 325px
  ![nrsz](https://cloud.githubusercontent.com/assets/12641346/12532110/93b991f0-c231-11e5-9576-1163d5c58ffb.PNG)

**Comment by yasoob** [comment]
Let me resolve these issues. :+1:

**Comment by Yathannsh** [comment]
Sure @yasoob!
You are the best suited to fix this, since you designed it :+1:
