### ISSUE TITLE
Overflowing of Names

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#624]
Large names overflow and hence overlap the following container :
![sd](https://cloud.githubusercontent.com/assets/12641346/12532147/70a8cac2-c232-11e5-8fab-050d61e2a4b0.PNG)

There are two ways to solve this problem: 
- Splice off the extra characters
- Add ellipsis after the letter the name starts overflowing, the same way it was implemented in the contributor's section:

![fds](https://cloud.githubusercontent.com/assets/12641346/12532170/dc04ce2e-c232-11e5-9293-019c6406dc70.PNG)

**Comment by yasoob** [comment]
This is simple to solve as well. Just add `overflow ellipsis` classes to `h4` name tags.

**Comment by Yathannsh** [comment]
@yasoob , yess'
Just looking for the best suited solution!
