### ISSUE TITLE
Non-responsive blog section 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#626]
![22](https://cloud.githubusercontent.com/assets/12641346/12532253/35278102-c235-11e5-906b-ac7e517cbf10.PNG)

**Comment by jigyasa-grover** [comment]
@Yathannsh Would you like to work on this ?

**Comment by Yathannsh** [comment]
@jig08 , sure I will try and fix this in a while!

**Comment by jigyasa-grover** [comment]
@Yathannsh Go ahead..
