### ISSUE TITLE
Lights out section issues 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#627]
1) This is how the section looks on small screen sizes:
![s](https://cloud.githubusercontent.com/assets/12641346/12532273/0087406c-c236-11e5-98f2-bffdcbf254ad.PNG)

2) There is a problem with avatar's placement 
![lo2](https://cloud.githubusercontent.com/assets/12641346/12532278/24aff560-c236-11e5-9aad-2509790fa8d0.PNG)

**Comment by mananwason** [comment]
@JamMurz would you like to work on this?

**Comment by jmurzaku** [comment]
@mananwason yes ill work on this

**Comment by mananwason** [comment]
@Yathannsh @JamMurz I don't think the button size or anything else in particular need improvement. You can maybe work on some kind of styling to make it look better but it seems good to me now also. Thanks for your contributions :smile:
