### ISSUE TITLE
G+ div is over-flowing on small screen sizes.

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#628]
G+ div is not responsive. This is causing the width of the html page to increase on small screen sizes. 

![img](https://cloud.githubusercontent.com/assets/12641346/12532199/cc056f6e-c233-11e5-9709-deae321907f2.PNG)

**Comment by jigyasa-grover** [comment]
@yasoob Would you like to work on this ?

**Comment by yasoob** [comment]
Sorry I wasn't here :smile: I will work on this tomorrow. :+1:

**Comment by mananwason** [comment]
:+1:
