### ISSUE TITLE
While clicking buttons in navbars

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#63]
While clicking buttons it shows something like this 
![before](https://cloud.githubusercontent.com/assets/8452800/11899327/64422432-a59e-11e5-8fed-1e4eea662476.jpg) But it should show
![after](https://cloud.githubusercontent.com/assets/8452800/11899352/85a3a54c-a59e-11e5-8b93-6b1654614c46.jpg)

**Comment by Meta-Maxim** [comment]
@PiotrKowalski I fixed this in pull #70 .

**Comment by mariobehling** [comment]
Thanks! Great work following up. Thank you.
