### ISSUE TITLE
Every contributor name is printing 2 times in contributors section.

### ISSUE THREAD

**Issue by shubh1m** [fossasia/gci15.fossasia.org#634]
![screenshot from 2016-01-24 04 53 40](https://cloud.githubusercontent.com/assets/13465950/12533490/b42fd0d2-c256-11e5-8708-546979bbb5b8.png)
![screenshot from 2016-01-24 04 53 54](https://cloud.githubusercontent.com/assets/13465950/12533491/b432fba4-c256-11e5-977f-87c26dba1114.png)

**Comment by jigyasa-grover** [comment]
Doesn't seem to be an issue on my end ....

**Comment by Yathannsh** [comment]
@jig08 same here! 
There was this issue a few hours back, seems to be resolved now. 
This is good to be closed :+1:

**Comment by mananwason** [comment]
Cool. Closing it. Could you maybe mention the commit number here @Yathannsh. Thanks !

**Comment by jig08** [comment]
Yes @Yathannsh  , as @yasoob had suggested mention `closes <Issue Number>` in your PR so that  it automatically does the needful :)

**Comment by Yathannsh** [comment]
@mananwason ,this was possibly a gh-pages build problem, was fixed by itself!

**Comment by mananwason** [comment]
Awesome!!
