### ISSUE TITLE
Contributor's Card Display issue 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#660]
Currently whilst hovering over any contributor's picture the whole place holder is highlighted, and the GitHub link is not appropriately display.
![2016-01-24](https://cloud.githubusercontent.com/assets/12641346/12536513/990af18e-c2cd-11e5-9ec9-1bf4d98db98c.png)

**Comment by jigyasa-grover** [comment]
@Yathannsh Help us improve this :)

**Comment by Yathannsh** [comment]
Sure here you go @jig08  #661  :smiley:

**Comment by jigyasa-grover** [comment]
Awesome !
