### ISSUE TITLE
Fix shadow for tweets from loklak 

### ISSUE THREAD

**Issue by mananwason** [fossasia/gci15.fossasia.org#662]
Looks like the tweets holder is at a greater height than the rest. 
<img width="1440" alt="screen shot 2016-01-24 at 7 22 21 pm" src="https://cloud.githubusercontent.com/assets/10570249/12536599/e9fb82f0-c2cf-11e5-9620-398ca47729e8.png">

**Comment by yasoob** [comment]
The `box-shadow` value is the same for all divs. :confused: Can you further clarify this issue please?

**Comment by mananwason** [comment]
Just look at it in the website. It visually looks like it is at a different height than the others. It even has some shadow on the fb badge below it.

**Comment by yasoob** [comment]
Should we just reduce the shadow for tweets div without interfering with other social divs then?

**Comment by mananwason** [comment]
Yeah I think that this should do the trick. Let's see.
