### ISSUE TITLE
New Images are greater than 240x240

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#671]
Most new contributors are uploading images which are greater than 240x240. In some cases they are greater than 1000px.

**Comment by mananwason** [comment]
@jig08 @SaptakS @samarjeet27 @nikunjness Please take care of size of the images while merging

**Comment by imharrymargalotti** [comment]
has this been fixed yet? i can resize the images

**Comment by mananwason** [comment]
Mostly @imharrymargalotti. @yasoob did add couple of resized images. But would be great if you can go through the images and find out if some of the images are still greater than 240x240. If yes you can resize them and create a PR. Cheers !

**Comment by yasoob** [comment]
@imharrymargalotti Just as @mananwason stated, there are still a couple of images which require re-sizing. Perhaps you can re-size them and submit a PR? :+1:

**Comment by mananwason** [comment]
@imharrymargalotti Are you working on this?

**Comment by imharrymargalotti** [comment]
yes, sorry i submitted my pull request, all photos are the proper size now and or a little smaller, and i converted some to .jpg in the process of resizing them

**Comment by abishekvashok** [comment]
@yasoob @mananwason we added a test to it it's called ImageChecker it integrates with travis via PR #741
