### ISSUE TITLE
Tasks to improve site speed

### ISSUE THREAD

**Issue by vicky002** [fossasia/gci15.fossasia.org#700]
- [ ] **Specifying a width and height for all images.**
     Specifying a width and height for all images allows for faster rendering by eliminating the need for unnecessary reflows and repaints.
- [x] **Defer parsing of JavaScript**: In order to load a page, the browser must parse the contents of all `<script>` tags, which adds additional time to the page load. By minimizing the amount of JavaScript needed to render the page, and deferring parsing of unneeded JavaScript until it needs to be executed, we can reduce the initial load time of your page.
- [ ]  **Server scaled images**: Properly sizing images can save many bytes of data.
- [x] **implement gzip compression** : Reduce the size of files sent from the server to increase the speed to which they are transferred to the browser. This can reduce sizes of pages by up to 70%. 
- [ ] **Write a documentation**:  On how to add your images in code, specify dimensions and max image size allowed.

Doc for reference : [Doc](https://docs.google.com/document/d/1JQve4vQSLSmdQUZicR5m0C0Pf8Zh9MBEs_s38fOj3Jg/edit?usp=sharing)

**Comment by vicky002** [comment]
@mananwason @jig08  This is what we need to do, this can improve the site speed by 30-40%.

**Comment by mananwason** [comment]
Awesome @vicky002. @jig08 @yasoob @codethejason We should start working on this. Cheers guys!

**Comment by jmurzaku** [comment]
@mananwason can i work on this too?

**Comment by mananwason** [comment]
@JamMurz go ahead :smile:

**Comment by jigyasa-grover** [comment]
Great suggestions @vicky002 .

**Comment by abishekvashok** [comment]
@jig08 hey can you help on how do we put on g-zip compression on jekyll. Googling is not helping

**Comment by jigyasa-grover** [comment]
I remember reading it somewhere that GitHub **gzip**'s the content automatically. 

Anyways, I did check the _HTTP Response Header_ of [gci15.fossasia.org](http://gci15.fossasia.org/) [here](http://www.rexswain.com/cgi-bin/httpview.cgi) and the result showed it to be true.

```
HTTP/1.1·200·OK(CR)(LF)
Date:·Thu,·28·Jan·2016·11:41:33·GMT(CR)(LF)
Content-Type:·text/html;·charset=utf-8(CR)(LF)
Transfer-Encoding:·chunked(CR)(LF)
Connection:·close(CR)(LF)
Set-Cookie:·__cfduid=dc913c5234a34cfd0ccc861033c5a00931453981293;·expires=Fri,·27-Jan-17·11:41:33·GMT;·path=/;·domain=.fossasia.org;·HttpOnly(CR)(LF)
Last-Modified:·Wed,·27·Jan·2016·22:58:46·GMT(CR)(LF)
Access-Control-Allow-Origin:·*(CR)(LF)
Expires:·Thu,·28·Jan·2016·11:51:33·GMT(CR)(LF)
Cache-Control:·max-age=600(CR)(LF)
X-GitHub-Request-Id:·C71B4F19:4968:EC2099:56A9FE6C(CR)(LF)
Via:·1.1·varnish(CR)(LF)
Age:·0(CR)(LF)
X-Served-By:·cache-lax1424-LAX(CR)(LF)
X-Cache:·MISS(CR)(LF)
X-Cache-Hits:·0(CR)(LF)
X-Timer:·S1453981293.295793,VS0,VE142(CR)(LF)
Vary:·Accept-Encoding(CR)(LF)
X-Fastly-Request-ID:·edb630894708910cb0c2cc5e084b4500744c0212(CR)(LF)
Server:·cloudflare-nginx(CR)(LF)
CF-RAY:·26bc6dcaff92065d-SJC(CR)(LF)
Content-Encoding:·gzip(CR)(LF)
(CR)(LF)

```

**Comment by vicky002** [comment]
Hi @jig08  This is great! I wasn't knowing this. Just read this : [GitHub as a CDN](http://code.lancepollard.com/github-as-a-cdn/) yeah GitHub gzip's content automatically! 

I'm marking that issue as done. :+1:

**Comment by abishekvashok** [comment]
So can we mark it as done @jig08 @vicky002 or remove that. Google is offering minimized code at page insights, so you want me to help out

**Comment by jigyasa-grover** [comment]
@vicky002 Cool !
@Abhi2424shek This sub-issue has been ticked off for now. So yes, Done.

**Comment by abishekvashok** [comment]
@jig08 I also think that most of the image tags in the code has the width and the height specified @vicky002 ! Any opinions

**Comment by vicky002** [comment]
@Abhi2424shek Please check the doc mentioned in the issue.

**Comment by abishekvashok** [comment]
@vicky002 got it. See my PR guys

**Comment by jmurzaku** [comment]
It appears a huge slow down to the website is the loklak heatmap

**Comment by abishekvashok** [comment]
@vicky002 got another PR, why not you too check it out @JamMurz - Defer parsing of JavaScript completed. check it at https://github.com/fossasia/gci15.fossasia.org/pull/717
