### ISSUE TITLE
Get the top right GCI menu image back

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#704]
- [x] There was a nice GCI image on the top right of the main menu. Please get it back in.
- [x] Move menu item "Github Issues" into submenu of students projects

**Comment by jigyasa-grover** [comment]
**`Check`** There was a nice GCI image on the top right of the main menu. Please get it back in. 
**`Check`** Move menu item "Github Issues" into submenu of students projects. 

@mariobehling Closing this Issue.
Nice work @codethejason :)
