### ISSUE TITLE
Move projects (that have a dedicated section) from student Gallery into a separate section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#710]
The "student gallery" is clustered. There are so many projects inside, that it is difficult to see, what cool projects are in there. Let's uncluster it.
- [ ] Move Mobile apps and Android projects into a new section "Mobile Apps" (and take them out of the student gallery)
- [ ] Move FOSS Quiz to a section "Quiz" and take them out of the gallery
- [ ] Move lights out to section "Lights Out" and delete them from the student gallery
- [ ] Move geolocation projects to section "geolocation" , e.g. "world distance location (and take them out of the gallery
- [ ] Move all blog posts to blog section and take them out of the gallery

**Comment by SilentFlame** [comment]
@mariobehling  
Is this task done, or can I start doing this?

**Comment by jigyasa-grover** [comment]
@SilentFlame The issue has not been resolved completely. There are certain projects in gallery which need to shifted to their dedicated sections. Also the nav arrows in the gallery do not seem to work any longer.

**Comment by SilentFlame** [comment]
@jig08
can you please guide me through the projects needed to be shifted to their dedicated sections.

As I can only see 1 project present in the Gallery section, and have no idea which section it really belongs to.
