### ISSUE TITLE
Mentors and students dont show 

### ISSUE THREAD

**Issue by jmurzaku** [fossasia/gci15.fossasia.org#712]
<img width="787" alt="screen shot 2016-01-27 at 4 15 37 pm" src="https://cloud.githubusercontent.com/assets/9733795/12628459/4005fc96-c511-11e5-87ea-2d7c357694e3.png">
anyone else having this issue?

**Comment by jigyasa-grover** [comment]
Yess !

**Comment by mananwason** [comment]
Yes !! Me too :confused:

**Comment by imharrymargalotti** [comment]
anyone know why this happened?

**Comment by yasoob** [comment]
I have tracked the issue and submitted the PR.

**Comment by mananwason** [comment]
Great @yasoob!!

**Comment by imharrymargalotti** [comment]
@yasoob what happened?

**Comment by mananwason** [comment]
@imharrymargalotti #713

**Comment by yasoob** [comment]
@imharrymargalotti Someone had removed 

```
---
---
```

from the start of `index.html` file. These lines are required by jekyll to render the page correctly. :)
