### ISSUE TITLE
Github Icons are Off Centered

### ISSUE THREAD

**Issue by codethejason** [fossasia/gci15.fossasia.org#718]
The Github icons in the contributor section are not vertically aligned after the avatar size change.  

![scrn](http://puu.sh/mOEsb/231730e384.jpg)

**Comment by abishekvashok** [comment]
Would get a fix @codethejason

**Comment by codethejason** [comment]
Cool @Abhi2424shek you can do it if you would like :).

**Comment by abishekvashok** [comment]
or you may too @codethejason

**Comment by jigyasa-grover** [comment]
So who's working on it ?

**Comment by abishekvashok** [comment]
@jig08 whom you want it to be on.

**Comment by codethejason** [comment]
@jig08 I can do it later if @Abhi2424shek isn't working on it. I thought he wanted to do it originally.

**Comment by abishekvashok** [comment]
@jig08 Ok i would take it up @codethejason , actually i thouht you were working on it .

**Comment by jigyasa-grover** [comment]
@codethejason Guess let @Abhi2424shek work on it ..

**Comment by codethejason** [comment]
@jig08 Sure no problem.

**Comment by jigyasa-grover** [comment]
:)
Hope you don't mind. 
You can certainly work on other issues ...

**Comment by abishekvashok** [comment]
Done guys @jig08 @codethejason , close this issue. I done it as the part of the PR: https://github.com/fossasia/gci15.fossasia.org/pull/724

**Comment by jigyasa-grover** [comment]
Hey @codethejason , Aint the PR still open ?
Let's wait till it gets merged :)

**Comment by codethejason** [comment]
Sorry @jig08, reopened!

**Comment by jigyasa-grover** [comment]
No issues ..

**Comment by abishekvashok** [comment]
@jig08 sorry for that I fetched a wrong code.. Would submit a new PR

**Comment by jigyasa-grover** [comment]
Okay.
