### ISSUE TITLE
Do we use style.scss file?

### ISSUE THREAD

**Issue by yasoob** [fossasia/gci15.fossasia.org#719]
Do we really utilize the [style.scss](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/scss/style.scss) file anywhere?

**Comment by abishekvashok** [comment]
scss files are used to be more powerful {They can include variables,nesting, mixins, inheritance etc}. They are compiled into css files.I think it's compiled in ruby. **I think it is used in the website**. You may see the code and **it looks like it controls the sliders**. So I think we have this done. But don't close unless the official word from the mentors arrive, got it @yasoob.

**Comment by roonyh** [comment]
I think @Yathannsh could give us this information. As he [authored it](https://github.com/fossasia/gci15.fossasia.org/blame/gh-pages/scss/style.scss)

**Comment by abishekvashok** [comment]
Let me try removing it and let me run some check locally. @roonyh the site seems that it does not need the scss file as the styles here seems locally ok without it. But I surely think that some css file in the stylesheets folder is a compiled version of it and that is why Yathnash put it there. But we will wait for the  words of Yathannsh :)
- Happy coding

**Comment by Abhi2424shek** [comment]
@roonyh the site it think does not need the scss file as the styles here seems locally ok without it. But I surely think that some css file in the stylesheets folder is a compiled version of it. But we will wait for the  words of Yathnash :)

**Comment by roonyh** [comment]
@Abhi2424shek Thanks for checking! yeah lets wait for @Yathannsh. I too don't think we use any scss files since we don't do any build step where we compile them to css. And github pages doesnt do this to the best of knowledge.

**Comment by abishekvashok** [comment]
Your's Welcome @roonyh . Let's wait for Yathannsh. I may give him a call or a message {I have his phone number}, if it's not low priority here.

**Comment by Yathannsh** [comment]
@yasoob @roonyh , we don't need the scss file now.
 I had authored it in CSS and kept a copy in SCSS as well keeping in mind a probable migration to SCSS. Now that we have the website working on CSS, I will send a commit to remove it. 
@Abhi2424shek , thanks for reaching out to me! :+1:

**Comment by abishekvashok** [comment]
@Yathannsh yours welcome, and @roonyh mind merging the change {the PR was pushed by Yathnash}
