### ISSUE TITLE
Loklak Tweet Search not working

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/gci15.fossasia.org#721]
The tweet search fails to retrieve data through ajax. 
Could someone recheck?

**Comment by Yathannsh** [comment]
Seems to work now, was a temporary server-side issue.

**Comment by abishekvashok** [comment]
@Yathannsh let me check

**Comment by abishekvashok** [comment]
@Yahannsh it's working please check it.
@jig08 @roony @mariobehling @mananwason - I think we could close this issue now since it is working fine!

**Comment by jigyasa-grover** [comment]
Yes. Seems to work just fine @Abhi2424shek .
@Yathannsh Closing this for now :)
