### ISSUE TITLE
GCI Site loading slowly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#731]
Find out why site is loading slower now and implement faster loading.

**Comment by Yathannsh** [comment]
The primary reason for the slow speed seems to be the large chunk of user data, specifically uncompressed images. Some loklak dependencies are also slowing down speed. Along with that minimizing JS, HTML & CSS will increase the speed and shouldn't be a problem to implement now as we don't have major changes being made onto them. @codethejason & I will push some fixes by tonight or figure out a work around to load the website faster for tomorrow's event.

**Comment by abishekvashok** [comment]
@mariobehling Its worked out
