### ISSUE TITLE
Contributors are not showing up

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci15.fossasia.org#734]
See the website, the contributors are not being shown, it will lead to trouble. I am getting in a PR

**Comment by abishekvashok** [comment]
See PR #736

**Comment by abishekvashok** [comment]
Since PR #736 is merged we could close this right @niccokunzmann

**Comment by abishekvashok** [comment]
I would need more work please wait till I get back. I would also fix the dialing Travis build, sorry for that I got the contributors section that is why I pushed a PR @niccokunzmann

**Comment by niccokunzmann** [comment]
@Abhi2424shek Yes, I see the contributors' section is filled. I will close it since you seem to agree!

**Comment by niccokunzmann** [comment]
@Abhi2424shek If you like to work more on this website, please create an issue for the things you see have to be done which describes the problem. 
After this, you can comment and be assigned to it if you like to work on it.
Somehow the contributors did not show up, after I merged the PR. Now they are visible, so I just closed the issue. If you have any questions, please ask :)

**Comment by abishekvashok** [comment]
@niccokunzmann it's not a problem and for my task accept when I get the Travis ok because I like to work. :)
