### ISSUE TITLE
Deleting Unecessary Information?

### ISSUE THREAD

**Issue by pipix51** [fossasia/gci15.fossasia.org#742]

**Comment by pipix51** [comment]
Should we delete the Loklak Peers section as well as the Lights Out button (only)? There are no more peers in the Loklak Peers section and the Lights Out button does not seem to have any effect on the webpage.

**Comment by abishekvashok** [comment]
@pipix51 fix the lights section it was created to have a javascript action which toogles the light on and off in the browser!!!

**Comment by jigyasa-grover** [comment]
@pipix51 Yes, both features used to work, pls fix them.
