### ISSUE TITLE
Facebook widget and blog posts overflowing

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci15.fossasia.org#746]
![image](https://cloud.githubusercontent.com/assets/19410489/21721603/4ec57f68-d429-11e6-9094-4f3afc781490.png)
![image](https://cloud.githubusercontent.com/assets/19410489/21721606/51233066-d429-11e6-8c67-d2090032914a.png)

We need to:
- [ ] Make Facebook widget responsive
- [ ] Make blog cards responsive

**Comment by myfrom** [comment]
Can I take it as part of this year GCI?

**Comment by abishekvashok** [comment]
Go on
