### ISSUE TITLE
Contributors section not showing images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#752]
The contributors section does not show all the images probably because of an API update. Please update the API calls and fix it.

![screenshot from 2018-02-01 23-08-29](https://user-images.githubusercontent.com/1583873/35706134-e814838a-07a4-11e8-9392-3f8868a4dc74.png)

**Comment by adi44** [comment]
This Issue has been already resolved. Please close it.

**Comment by adsk261095** [comment]
@mariobehling is the issue still open??
