### ISSUE TITLE
Align the footer content properly in one single line.

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/gci15.fossasia.org#77]
<img width="1438" alt="screen shot 2015-12-19 at 2 29 45 pm" src="https://cloud.githubusercontent.com/assets/4545925/11912763/0d290976-a65d-11e5-944c-1e22f9280c32.png">

The best thing to do here would be to align the social icons to the left/right and the text in the same line to the other side.

**Comment by PiotrKowalski** [comment]
Do you mean something like this?
![6escgi](https://cloud.githubusercontent.com/assets/8452800/11913413/28f7e00e-a663-11e5-8193-1dd0a36c6d5c.jpg)

It repairs bad look on mobile phones too. Before PR it looks like it. 
![screenshot_2015-12-19-16-20-17_1450538436431](https://cloud.githubusercontent.com/assets/8452800/11913686/8a5553fa-a66c-11e5-8928-ecb39acd5785.jpg)
After PR: 
![screenshot_2015-12-19-19-52-03_1450551171936](https://cloud.githubusercontent.com/assets/8452800/11914813/2d26934c-a68a-11e5-985d-d2728fa777e3.jpg)
Demo: http://piotrkowalski.github.io/gci15.fossasia.org/
