### ISSUE TITLE
Proposal: Make fossasia.org http to https

### ISSUE THREAD

**Issue by mkarjun** [fossasia/gci15.fossasia.org#785]
It would be good if we make the site ssl certified. Feel free to close the issue. I'm new to opensource , just thought why its not secured.

**Comment by Manish-Syal123** [comment]
can you please tell me that where this site is hosted.

**Comment by mkarjun** [comment]
The site is hosted with Cloudflare. @Manish-Syal123 

From my analysis, I think the site is not in use as its GCI 2015 
As the issue remains of no significance closing the issue

**Comment by Manish-Syal123** [comment]
Thanks for info
