### ISSUE TITLE
Contributors' logo should have animation

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#79]
It should have animation like mentors' and students' logo. It looks too bad
![3e1h0w3n6](https://cloud.githubusercontent.com/assets/8452800/11913548/9a9a70ce-a667-11e5-98d9-5657c5972f3d.jpg)

**Comment by codethejason** [comment]
It might be designed like that to avoid repetitive information presented in the earlier sections. I do see your point as some of the contributors are neither mentors nor GCI students.

**Comment by Meta-Maxim** [comment]
Yes, it was meant to be that way to prevent repeating the same info like @codethejason said. If there are people on it who are not in GCI/Fossasia, then we don't want to give out their information other than their Github profile since we don't know if they wanted this or not when they contributed.
