### ISSUE TITLE
Unnecessary padding

### ISSUE THREAD

**Issue by seadog007** [fossasia/gci15.fossasia.org#86]
<img width="1280" alt="2015-12-20 2 03 45" src="https://cloud.githubusercontent.com/assets/5138409/11914517/1087434c-a6be-11e5-9479-357d2cb6bb1c.png">

**Comment by PiotrKowalski** [comment]
I made it by accident xD I wanted only do #81 :D
http://piotrkowalski.github.io/gci15.fossasia.org/#social_media
