### ISSUE TITLE
G+ section align problem

### ISSUE THREAD

**Issue by seadog007** [fossasia/gci15.fossasia.org#87]
<img width="723" alt="2015-12-20 2 03 38" src="https://cloud.githubusercontent.com/assets/5138409/11914520/54d882d6-a6be-11e5-8836-937a0a635338.png">

It should be align in center, but if it can fill whole space, then it will be better.

**Comment by Meta-Maxim** [comment]
@seadog007 It can't fill the whole space. Google restricts it to either a portrait (150px) or landscape (240px) size.

**Comment by sudheesh001** [comment]
I believe this is fixed, the card is center aligned.
