### ISSUE TITLE
Bad width to media section on mobile phones

### ISSUE THREAD

**Issue by PiotrKowalski** [fossasia/gci15.fossasia.org#91]
My code from #81 didn't repair bad scaling on mobile phones with FB, YT and G+. It looks like it: 

![screenshot_2015-12-20-00-15-01](https://cloud.githubusercontent.com/assets/8452800/11915698/60f93a20-a6b3-11e5-8c10-d7d06e805aac.png)

![screenshot_2015-12-20-00-15-07](https://cloud.githubusercontent.com/assets/8452800/11915693/f7b05d5a-a6b2-11e5-8811-67ed59916d2d.png)

I didn't notice it.

**Comment by aayusharora** [comment]
I have done it here #244,it is shown in snapshot ,looks fine to me now
![9](https://cloud.githubusercontent.com/assets/12194719/12012148/5866b12e-ad0e-11e5-9026-a647c25d7858.PNG)

**Comment by mananwason** [comment]
@aayusharora @PiotrKowalski I beleive that it has been fixed already.
![screenshot_20151228-101021](https://cloud.githubusercontent.com/assets/10570249/12014096/5581229a-ad4b-11e5-838d-240637319c5e.png)

**Comment by aayusharora** [comment]
@manomwason,I am not sure as when I was minimising my browsers window to 321 px ,I got the gplus page loaded which I have corrected ,but in your snapshot the image is not loading its something else which comes when there is not proper loading ,pls check once again.

**Comment by aayusharora** [comment]
@mananwason,I am not sure as when I was minimising my browsers window to 321 px ,I got the gplus page loaded which I have corrected ,but in your snapshot the image is not loading its something else which comes when there is not proper loading ,pls check once again.

**Comment by aayusharora** [comment]
@mananwason,I have also shown how it is looking on my page in my previous snapshot

**Comment by mananwason** [comment]
@aayusharora what image is not being loaded in my screenshot. Could you elaborate?

**Comment by aayusharora** [comment]
@mananwason ,when resizing my browsers window to mobile view ,I am getting the gplus portion like 
![9](https://cloud.githubusercontent.com/assets/12194719/12048813/e5b65bf8-af05-11e5-9074-a108aeb12ec4.PNG)

**Comment by aayusharora** [comment]
@mananwason ,but according to you ,it would be like ,which I think is not loading correctly
![10](https://cloud.githubusercontent.com/assets/12194719/12048831/14fe936c-af06-11e5-95b7-e45e870359b0.PNG)

**Comment by aayusharora** [comment]
@jig08 ,@mananwason I think it is corrected now ,have checked it at many screen sizes ,we can close this.
![12](https://cloud.githubusercontent.com/assets/12194719/12113629/e1478358-b3c9-11e5-90c4-9f8de911e587.PNG)

**Comment by jigyasa-grover** [comment]
Cool, closing for now.
