### ISSUE TITLE
Scroll Bar Problem

### ISSUE THREAD

**Issue by codethejason** [fossasia/gci15.fossasia.org#96]
This is related to issue #92 . After adding the top margin of the body element, everything is pushed down, so the bottom scroll button cannot be clicked:  

![scroll](http://puu.sh/m1RGg/e0e0f46c74.png).

**Comment by Meta-Maxim** [comment]
Fixing... Have to make HTML scrollable not body, I'l  push tomorrow.

**Comment by pythad** [comment]
Also footer can't be seen now because of this:
![selection_010](https://cloud.githubusercontent.com/assets/10961029/11917181/b9ec2c22-a704-11e5-8c06-e00cc2d0688b.png)

**Comment by Meta-Maxim** [comment]
@codethejason Fixed, close the issue. DEMO: http://maxborsch.github.io/gci15.fossasia.org/
